#!/usr/bin/env python3
"""Generate one Tensile input yaml per registered gfx1151 CMS schedule.

Per `Tensile/Components/CustomSchedule.py` lines ~5594-7592, 31 schedules are
registered for ISA=(11,5,1). Each `RegisterSchedule` decorator pins a complete
(MT0, MT1, DepthU, PGR, PLR, DTL, DPLB, WSGRA, WSGRB, MI, MIWG, vector_widths,
dtype_predicate) tuple. We materialize each as an input-yaml that produces
exactly one solution matching that tuple.

Source-format reference: Tensile input yamls under
`Tensile/Tests/common/gemm/gfx11/*.yaml` (e.g. fp16_tn_gfx11.yaml). Format
documented in `Tensile/Common/GlobalParameters.py` and parsed at
`Tensile/SolutionStructs/Solution.py`.

MatrixInstruction 9-element format:
   [MI_M, MI_N, MI_K, MI_B, factor, MIWaveTileA, MIWaveTileB, MIWGM, MIWGN]
(per `Tensile/SolutionStructs/Validators/MatrixInstruction.py:73-121`)
"""
import os
import textwrap

# (function_name, MT0, MT1, DU, PGR, PLR, MIWGM, MIWGN, GRVWA, GRVWB, LRVW, MI_K, line)
SCHEDULES = [
    ("_get_schedule_96x128x32_16bit_gfx1151",            96, 128,  32, 2, 1, 2, 2, 8, 8, 16, 16, 5594),
    ("_get_schedule_128x96x32_16bit_gfx1151",           128,  96,  32, 2, 1, 2, 2, 8, 8, 16, 16, 5657),
    ("_get_schedule_192x64x32_16bit_gfx1151",           192,  64,  32, 2, 1, 4, 1, 8, 8, 16, 16, 5719),
    ("_get_schedule_64x192x32_16bit_gfx1151",            64, 192,  32, 2, 1, 1, 4, 8, 8, 16, 16, 5781),
    ("_get_schedule_32x128x64_16bit_gfx1151",            32, 128,  64, 2, 1, 1, 4, 8, 8, 16, 16, 5844),
    ("_get_schedule_96x128x64_plr0_14_16bit_gfx1151",    96, 128,  64, 2, 0, 2, 2, 8, 8, 16, 16, 5922),
    ("_get_schedule_128x64x64_plr1_16bit_gfx1151",      128,  64,  64, 2, 1, 2, 2, 8, 8, 16, 16, 5995),
    ("_get_schedule_128x80x64_16bit_gfx1151",           128,  80,  64, 2, 1, 4, 1, 8, 8, 16, 16, 6068),
    ("_get_schedule_128x80x64_pgr1_16bit_gfx1151",      128,  80,  64, 1, 1, 4, 1, 8, 8, 16, 16, 6145),
    ("_get_schedule_64x128x32_14_16bit_gfx1151",         64, 128,  32, 2, 1, 1, 4, 8, 8, 16, 16, 6212),
    ("_get_schedule_128x64x32_16bit_gfx1151",           128,  64,  32, 2, 1, 4, 1, 8, 8, 16, 16, 6268),
    ("_get_schedule_64x128x32_22_16bit_gfx1151",         64, 128,  32, 2, 1, 2, 2, 8, 8, 16, 16, 6324),
    ("_get_schedule_96x96x32_16bit_gfx1151",             96,  96,  32, 2, 1, 2, 2, 8, 8, 16, 16, 6384),
    ("_get_schedule_64x64x32_22_16bit_gfx1151",          64,  64,  32, 2, 1, 2, 2, 8, 8, 16, 16, 6463),
    ("_get_schedule_16x16x128_16bit_gfx1151",            16,  16, 128, 2, 1, 1, 1, 8, 8, 16, 16, 6529),
    ("_get_schedule_32x16x128_16bit_gfx1151",            32,  16, 128, 2, 1, 2, 1, 8, 8, 16, 16, 6616),
    ("_get_schedule_128x96x64_plr0_41_16bit_gfx1151",   128,  96,  64, 2, 0, 4, 1, 8, 8, 16, 16, 6703),
    ("_get_schedule_96x128x64_plr0_14_16bit_gfx1151_tn", 96, 128,  64, 2, 0, 1, 4, 8, 8, 16, 16, 6765),
    ("_get_schedule_128x112x32_plr0_16bit_gfx1151",     128, 112,  32, 2, 0, 4, 1, 8, 4, 16, 16, 6827),
    ("_get_schedule_128x80x64_plr0_16bit_gfx1151",      128,  80,  64, 2, 0, 4, 1, 8, 8, 16, 16, 6885),
    ("_get_schedule_128x80x64_pgr1_plr1_16bit_gfx1151", 128,  80,  64, 1, 1, 4, 1, 8, 8, 16, 16, 6952),
    ("_get_schedule_80x128x64_pgr2_plr1_16bit_gfx1151",  80, 128,  64, 2, 1, 1, 4, 8, 8, 16, 16, 7020),
    ("_get_schedule_80x128x64_pgr2_plr0_16bit_gfx1151",  80, 128,  64, 2, 0, 1, 4, 8, 8, 16, 16, 7084),
    ("_get_schedule_64x224x32_pgr2_plr0_16bit_gfx1151",  64, 224,  32, 2, 0, 2, 2, 8, 8, 16, 16, 7153),
    ("_get_schedule_128x64x32_pgr2_plr0_16bit_gfx1151", 128,  64,  32, 2, 0, 2, 2, 8, 8, 16, 16, 7212),
    ("_get_schedule_128x48x32_pgr2_plr1_16bit_gfx1151", 128,  48,  32, 2, 1, 4, 1, 8, 4, 16, 16, 7271),
    ("_get_schedule_64x32x64_pgr2_plr1_16bit_gfx1151",   64,  32,  64, 2, 1, 2, 2, 8, 8, 16, 16, 7331),
    ("_get_schedule_128x96x32_pgr1_plr0_16bit_gfx1151", 128,  96,  32, 1, 0, 2, 2, 8, 8, 16, 16, 7401),
    ("_get_schedule_128x96x64_pgr2_plr0_22_16bit_gfx1151", 128, 96, 64, 2, 0, 2, 2, 8, 8, 16, 16, 7458),
    ("_get_schedule_128x64x64_pgr2_plr0_22_16bit_gfx1151", 128, 64, 64, 2, 0, 2, 2, 8, 8, 16, 16, 7521),
    ("_get_schedule_128x64x64_pgr1_plr0_22_16bit_gfx1151", 128, 64, 64, 1, 0, 2, 2, 8, 8, 16, 16, 7584),
]

YAML_TEMPLATE = """\
# Auto-generated per-schedule input yaml for gfx1151 CMS validation.
#
# Generated by Tensile/Components/GFX1151_AUDIT/per_schedule_yamls/gen_yamls.py
# (see also README.md in the same directory).
#
# This yaml exercises EXACTLY ONE registered CMS schedule:
#   {fname}
# at CustomSchedule.py:{line} on branch users/alvasile/validator_long_term_plans.
#
# Schedule parameters (must match the @RegisterSchedule decorator):
#   MacroTile          : {mt0}x{mt1}x{du}
#   PrefetchGlobalRead : {pgr}
#   PrefetchLocalRead  : {plr}
#   DirectToLds        : 0
#   DtlPlusLdsBuf      : False
#   WaveSeparateGlobalReadA/B : 0/0
#   ISA                : (11, 5, 1)
#   WavefrontSize      : 32
#   MatrixInstruction  : [16, 16, {mik}, 1]
#   MIWaveGroup        : [{wgm}, {wgn}]
#   MIWaveTile (A, B)  : ({wta}, {wtb})
#   GlobalReadVectorWidth A/B : {grvwa}/{grvwb}
#   LocalReadVectorWidth      : {lrvw}
#   dtype_predicate    : is16bit (h/bf16; we use h, TN layout)
#
# Source format version: Tensile input yaml as parsed by SolutionStructs/Solution.py
# on commit {commit_tip} (g4w tip of users/alvasile/validator_long_term_plans).

TestParameters:
  marks: [skip-gfx900, skip-gfx906, skip-gfx908, skip-gfx90a, skip-gfx940, skip-gfx941, skip-gfx942, skip-gfx950, skip-gfx1010, skip-gfx1011, skip-gfx1012, skip-gfx1030, skip-gfx1100, skip-gfx1101, skip-gfx1102, skip-gfx1200, skip-gfx1201, skip-gfx1250]

GlobalParameters:
  MinimumRequiredVersion: 5.0.0
  CMakeBuildType: Release
  EnqueuesPerSync: 1
  SyncsPerBenchmark: 0
  NumElementsToValidate: 128
  BoundsCheck: False
  KernelTime: True
  NewClient: 2
  PrintSolutionRejectionReason: True
  Device: 0

BenchmarkProblems:
  -
    - # ProblemType (TN, fp16 in / fp32 compute -- matches the registry's is16bit predicate)
      OperationType: GEMM
      DataType: h
      DestDataType: h
      ComputeDataType: s
      HighPrecisionAccumulate: True
      TransposeA: True
      TransposeB: False
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup -- one solution that exactly matches the schedule
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - KernelLanguage: ["Assembly"]
      ForkParameters:
        # MatrixInstruction 9-element form:
        #   [MI_M, MI_N, MI_K, MI_B, factor, MIWaveTileA, MIWaveTileB, MIWGM, MIWGN]
        - MatrixInstruction:
          - [16, 16, {mik}, 1, 1, {wta}, {wtb}, {wgm}, {wgn}]
        - WavefrontSize: [32]
        - DepthU: [{du}]
        - PrefetchGlobalRead: [{pgr}]
        - PrefetchLocalRead: [{plr}]
        - VectorWidthA: [1]
        - VectorWidthB: [1]
        - GlobalReadVectorWidthA: [{grvwa}]
        - GlobalReadVectorWidthB: [{grvwb}]
        - LocalReadVectorWidth: [{lrvw}]
        - TransposeLDS: [1]
        - DirectToLds: [0]
        - WaveSeparateGlobalReadA: [0]
        - WaveSeparateGlobalReadB: [0]
        - ScheduleIterAlg: [3]
        - UseCustomMainLoopSchedule: [1]
        - GlobalSplitU: [1]
        - StaggerU: [0]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Exact: [{m}, {n}, 1, {k}]
"""

# fixed commit-tip identifier (g4w)
COMMIT_TIP = "0052629546"

OUTDIR = os.environ.get("OUTDIR")
if not OUTDIR:
    raise SystemExit("Set OUTDIR")

os.makedirs(OUTDIR, exist_ok=True)

def derive_wt(mt, mi, wg):
    assert mt % (mi * wg) == 0, f"MT={mt} not divisible by MI={mi}*WG={wg}"
    return mt // (mi * wg)

count = 0
for s in SCHEDULES:
    fname, mt0, mt1, du, pgr, plr, wgm, wgn, grvwa, grvwb, lrvw, mik, line = s
    wta = derive_wt(mt0, 16, wgm)
    wtb = derive_wt(mt1, 16, wgn)
    # Pick problem sizes large enough for one full macro tile
    m = max(mt0, 256)
    n = max(mt1, 256)
    k = max(du, 256)
    out = YAML_TEMPLATE.format(
        fname=fname, mt0=mt0, mt1=mt1, du=du, pgr=pgr, plr=plr,
        wgm=wgm, wgn=wgn, wta=wta, wtb=wtb,
        grvwa=grvwa, grvwb=grvwb, lrvw=lrvw, mik=mik,
        line=line, commit_tip=COMMIT_TIP,
        m=m, n=n, k=k,
    )
    out_path = os.path.join(OUTDIR, fname + ".yaml")
    with open(out_path, "w") as f:
        f.write(out)
    count += 1
    print(f"  {fname}.yaml  MT={mt0}x{mt1}x{du} PGR={pgr} PLR={plr} MIWG=[{wgm},{wgn}] WT=[{wta},{wtb}] GRVW=[{grvwa},{grvwb}] LRVW={lrvw} MIK={mik}")

print(f"Wrote {count} yamls under {OUTDIR}")
