// Copyright (c) Advanced Micro Devices, Inc., or its affiliates.
// SPDX-License-Identifier: MIT

/**
 * @file test_pooling_bwd_simple.cpp
 * @brief Unit tests for pooling-bwd kernels generated by
 *        pooling_bwd_instance_builder.
 */

#include <gtest/gtest.h>

#include <iostream>
#include <string>
#include <string_view>
#include <vector>

#include "ck_tile/core.hpp"
#include "ck_tile/host.hpp"
#include "ck_tile/ops/pooling.hpp"
#include "ck_tile/ops/pooling_bwd.hpp"
#include "ck_tile/host/reference/reference_pool.hpp"
#include "ck_tile/host/reference/reference_pool_bwd.hpp"

// The bwd kernel header is included via -include flag and defines
// SelectedKernel, KERNEL_NAME, DInDataType, DOutDataType, ComputeDataType,
// IndexDataType, TensorShape, WindowShape, POOLING_BWD_DIM.

struct PoolBwdTestParams2D
{
    int N, H, W, C;
    int Y, X;
    int stride_h, stride_w;
    int dilation_h, dilation_w;
    int pad_h_left, pad_h_right;
    int pad_w_left, pad_w_right;
};

struct PoolBwdTestParams3D
{
    int N, D, H, W, C;
    int Z, Y, X;
    int stride_d, stride_h, stride_w;
    int dilation_d, dilation_h, dilation_w;
    int pad_d_left, pad_d_right;
    int pad_h_left, pad_h_right;
    int pad_w_left, pad_w_right;
};

#ifdef POOLING_BWD_TEST_PARAMS_HPP
#include POOLING_BWD_TEST_PARAMS_HPP
#endif

// Dtype-aware verification tolerances. Defined once at file scope so both the
// 2D and 3D test branches can reuse them.
static double pool_bwd_rtol_for_dtype()
{
    if constexpr(std::is_same_v<DInDataType, float>)
        return 1e-5;
    else if constexpr(std::is_same_v<DInDataType, ck_tile::half_t> ||
                      std::is_same_v<DInDataType, ck_tile::bf16_t>)
        return 1e-2;
    else
        return 1e-1;
}

static double pool_bwd_atol_for_dtype()
{
    if constexpr(std::is_same_v<DInDataType, float>)
        return 1e-5;
    else if constexpr(std::is_same_v<DInDataType, ck_tile::half_t> ||
                      std::is_same_v<DInDataType, ck_tile::bf16_t>)
        return 1e-2;
    else
        return 1e-1;
}

#if POOLING_BWD_DIM_VALUE == 2

class PoolingBwdTileEngineTest2D : public ::testing::TestWithParam<PoolBwdTestParams2D>
{
    protected:
    void SetUp() override
    {
        auto p       = GetParam();
        N_           = p.N;
        H_           = p.H;
        W_           = p.W;
        C_           = p.C;
        Y_           = p.Y;
        X_           = p.X;
        stride_h_    = p.stride_h;
        stride_w_    = p.stride_w;
        dilation_h_  = p.dilation_h;
        dilation_w_  = p.dilation_w;
        pad_h_left_  = p.pad_h_left;
        pad_h_right_ = p.pad_h_right;
        pad_w_left_  = p.pad_w_left;
        pad_w_right_ = p.pad_w_right;

        const ck_tile::index_t Ys = (Y_ - 1) * dilation_h_ + 1;
        const ck_tile::index_t Xs = (X_ - 1) * dilation_w_ + 1;
        Ho_                       = (H_ + pad_h_left_ + pad_h_right_ - Ys) / stride_h_ + 1;
        Wo_                       = (W_ + pad_w_left_ + pad_w_right_ - Xs) / stride_w_ + 1;
    }

    int N_, H_, W_, C_;
    int Y_, X_;
    int stride_h_, stride_w_;
    int dilation_h_, dilation_w_;
    int pad_h_left_, pad_h_right_;
    int pad_w_left_, pad_w_right_;
    int Ho_, Wo_;
};

TEST_P(PoolingBwdTileEngineTest2D, BasicFunctionality)
{
    const bool kernel_is_overlap = SelectedKernel::kHasOverlap;
    const bool problem_overlap =
        ((Y_ - 1) * dilation_h_ + 1) > stride_h_ || ((X_ - 1) * dilation_w_ + 1) > stride_w_;
    if(kernel_is_overlap != problem_overlap)
    {
        GTEST_SKIP() << "Kernel overlap mode (" << kernel_is_overlap
                     << ") does not match problem overlap (" << problem_overlap << ")";
    }

    using InDataType  = DInDataType;
    using OutDataType = DOutDataType;

    ck_tile::HostTensor<InDataType> h_in({N_, H_, W_, C_});
    ck_tile::HostTensor<OutDataType> h_out({N_, Ho_, Wo_, C_});
    ck_tile::HostTensor<IndexDataType> h_indices({N_, Ho_, Wo_, C_});
    ck_tile::HostTensor<DOutDataType> h_dout({N_, Ho_, Wo_, C_});
    ck_tile::HostTensor<DInDataType> h_din({N_, H_, W_, C_});
    ck_tile::HostTensor<DInDataType> h_din_ref({N_, H_, W_, C_});

    ck_tile::FillUniformDistribution<InDataType>{-5.f, 5.f}(h_in);
    ck_tile::FillUniformDistribution<DOutDataType>{-1.f, 1.f}(h_dout);

    ck_tile::DeviceMem d_in(h_in.get_element_space_size_in_bytes());
    ck_tile::DeviceMem d_out(h_out.get_element_space_size_in_bytes());
    ck_tile::DeviceMem d_indices(h_indices.get_element_space_size_in_bytes());
    ck_tile::DeviceMem d_dout(h_dout.get_element_space_size_in_bytes());
    ck_tile::DeviceMem d_din(h_din.get_element_space_size_in_bytes());

    d_in.ToDevice(h_in.data());
    d_dout.ToDevice(h_dout.data());

    const auto input_shape    = ck_tile::make_tuple(N_, H_, W_, C_);
    const auto output_shape   = ck_tile::make_tuple(N_, Ho_, Wo_, C_);
    const auto input_strides  = ck_tile::make_tuple(H_ * W_ * C_, W_ * C_, C_, 1);
    const auto output_strides = ck_tile::make_tuple(Ho_ * Wo_ * C_, Wo_ * C_, C_, 1);
    const auto window_lengths = ck_tile::make_tuple(Y_, X_);
    const auto window_strides = ck_tile::make_tuple(stride_h_, stride_w_);
    const auto window_dils    = ck_tile::make_tuple(dilation_h_, dilation_w_);
    const auto left_pads      = ck_tile::make_tuple(pad_h_left_, pad_w_left_);
    const auto right_pads     = ck_tile::make_tuple(pad_h_right_, pad_w_right_);

    using ReduceOp   = ck_tile::ReduceOp::Max;
    using BlockWarps = ck_tile::sequence<1, 1>;
    using BlockTile  = ck_tile::sequence<128, 1>;
    using WarpTile   = ck_tile::sequence<128, 1>;
    using ThreadTile = ck_tile::sequence<2, 1>;
    using FwdShape   = ck_tile::PoolShape<BlockWarps, BlockTile, WarpTile, ThreadTile>;
    using FwdProblem = ck_tile::PoolProblem<InDataType,
                                            OutDataType,
                                            ComputeDataType,
                                            IndexDataType,
                                            ReduceOp,
                                            true,
                                            false,
                                            FwdShape>;
    using FwdKernel  = ck_tile::PoolKernel<FwdProblem>;

    auto fwd_host_args = ck_tile::PoolHostArgs<decltype(input_shape), decltype(window_lengths)>{
        d_in.GetDeviceBuffer(),
        d_out.GetDeviceBuffer(),
        d_indices.GetDeviceBuffer(),
        input_shape,
        output_shape,
        input_strides,
        output_strides,
        window_lengths,
        window_strides,
        window_dils,
        left_pads,
        right_pads};
    auto fwd_kargs = FwdKernel::MakeKernelArgs(fwd_host_args);

    if(!FwdKernel::IsSupportedArgument(fwd_kargs))
    {
        GTEST_SKIP() << "Forward pool arguments not supported.";
    }

    constexpr ck_tile::index_t kFwdBlockPerCu = 1;
    const ck_tile::index_t fwd_grid_size      = FwdKernel::CalculateGridSize(fwd_kargs);
    const ck_tile::index_t fwd_block_size     = FwdKernel::BlockSize();

    ck_tile::launch_kernel(ck_tile::stream_config{nullptr, false, 0},
                           ck_tile::make_kernel<kFwdBlockPerCu>(
                               FwdKernel{}, fwd_grid_size, fwd_block_size, 0, fwd_kargs));

    const ck_tile::long_index_t din_length =
        static_cast<ck_tile::long_index_t>(h_din.get_element_space_size());
    const ck_tile::long_index_t dout_length =
        static_cast<ck_tile::long_index_t>(h_dout.get_element_space_size());

    const std::size_t workspace_bytes = SelectedKernel::BwdKernel::GetWorkSpaceSize(
        ck_tile::PoolBwdHostArgs{
            nullptr, nullptr, nullptr, nullptr, dout_length, din_length, problem_overlap});
    ck_tile::DeviceMem d_workspace(workspace_bytes);

    ck_tile::PoolBwdHostArgs bwd_host_args{d_dout.GetDeviceBuffer(),
                                           d_indices.GetDeviceBuffer(),
                                           d_din.GetDeviceBuffer(),
                                           workspace_bytes > 0 ? d_workspace.GetDeviceBuffer()
                                                               : nullptr,
                                           dout_length,
                                           din_length,
                                           problem_overlap};

    ck_tile::stream_config stream{nullptr, false, 0, 0, 1, false, false, 1};

    try
    {
        SelectedKernel::launch(bwd_host_args, stream);
    }
    catch(const std::exception& e)
    {
        const std::string msg(e.what());
        if(msg.find("Unsupported arguments") != std::string::npos)
        {
            GTEST_SKIP() << "Configuration not supported: " << e.what();
        }
        FAIL() << "Bwd kernel launch failed: " << e.what();
    }

    d_indices.FromDevice(h_indices.data());
    d_din.FromDevice(h_din.data());

    ck_tile::reference_pool_bwd<DOutDataType, IndexDataType, ComputeDataType, DInDataType>(
        h_dout, h_indices, h_din_ref);

    const bool pass = ck_tile::check_err(
        h_din, h_din_ref, "Error: Incorrect dx", pool_bwd_rtol_for_dtype(), pool_bwd_atol_for_dtype());
    EXPECT_TRUE(pass) << "Pooling bwd verification failed for " << KERNEL_NAME;
}

INSTANTIATE_TEST_SUITE_P(PoolingBwdVerification,
                         PoolingBwdTileEngineTest2D,
                         ::testing::ValuesIn(CONFIG_TEST_PARAMS),
                         [](const ::testing::TestParamInfo<PoolBwdTestParams2D>& param_info) {
                             return "N" + std::to_string(param_info.param.N) + "_H" +
                                    std::to_string(param_info.param.H) + "_W" +
                                    std::to_string(param_info.param.W) + "_C" +
                                    std::to_string(param_info.param.C) + "_Y" +
                                    std::to_string(param_info.param.Y) + "_X" +
                                    std::to_string(param_info.param.X);
                         });

#elif POOLING_BWD_DIM_VALUE == 3

class PoolingBwdTileEngineTest3D : public ::testing::TestWithParam<PoolBwdTestParams3D>
{
    protected:
    void SetUp() override
    {
        auto p       = GetParam();
        N_           = p.N;
        D_           = p.D;
        H_           = p.H;
        W_           = p.W;
        C_           = p.C;
        Z_           = p.Z;
        Y_           = p.Y;
        X_           = p.X;
        stride_d_    = p.stride_d;
        stride_h_    = p.stride_h;
        stride_w_    = p.stride_w;
        dilation_d_  = p.dilation_d;
        dilation_h_  = p.dilation_h;
        dilation_w_  = p.dilation_w;
        pad_d_left_  = p.pad_d_left;
        pad_d_right_ = p.pad_d_right;
        pad_h_left_  = p.pad_h_left;
        pad_h_right_ = p.pad_h_right;
        pad_w_left_  = p.pad_w_left;
        pad_w_right_ = p.pad_w_right;

        const ck_tile::index_t Zs = (Z_ - 1) * dilation_d_ + 1;
        const ck_tile::index_t Ys = (Y_ - 1) * dilation_h_ + 1;
        const ck_tile::index_t Xs = (X_ - 1) * dilation_w_ + 1;
        Do_                       = (D_ + pad_d_left_ + pad_d_right_ - Zs) / stride_d_ + 1;
        Ho_                       = (H_ + pad_h_left_ + pad_h_right_ - Ys) / stride_h_ + 1;
        Wo_                       = (W_ + pad_w_left_ + pad_w_right_ - Xs) / stride_w_ + 1;
    }

    int N_, D_, H_, W_, C_;
    int Z_, Y_, X_;
    int stride_d_, stride_h_, stride_w_;
    int dilation_d_, dilation_h_, dilation_w_;
    int pad_d_left_, pad_d_right_;
    int pad_h_left_, pad_h_right_;
    int pad_w_left_, pad_w_right_;
    int Do_, Ho_, Wo_;
};

TEST_P(PoolingBwdTileEngineTest3D, BasicFunctionality)
{
    const bool kernel_is_overlap = SelectedKernel::kHasOverlap;
    const bool problem_overlap   = ((Z_ - 1) * dilation_d_ + 1) > stride_d_ ||
                                 ((Y_ - 1) * dilation_h_ + 1) > stride_h_ ||
                                 ((X_ - 1) * dilation_w_ + 1) > stride_w_;
    if(kernel_is_overlap != problem_overlap)
    {
        GTEST_SKIP() << "Kernel overlap mode (" << kernel_is_overlap
                     << ") does not match problem overlap (" << problem_overlap << ")";
    }

    using InDataType  = DInDataType;
    using OutDataType = DOutDataType;

    ck_tile::HostTensor<InDataType> h_in({N_, D_, H_, W_, C_});
    ck_tile::HostTensor<OutDataType> h_out({N_, Do_, Ho_, Wo_, C_});
    ck_tile::HostTensor<IndexDataType> h_indices({N_, Do_, Ho_, Wo_, C_});
    ck_tile::HostTensor<DOutDataType> h_dout({N_, Do_, Ho_, Wo_, C_});
    ck_tile::HostTensor<DInDataType> h_din({N_, D_, H_, W_, C_});
    ck_tile::HostTensor<DInDataType> h_din_ref({N_, D_, H_, W_, C_});

    ck_tile::FillUniformDistribution<InDataType>{-5.f, 5.f}(h_in);
    ck_tile::FillUniformDistribution<DOutDataType>{-1.f, 1.f}(h_dout);

    ck_tile::DeviceMem d_in(h_in.get_element_space_size_in_bytes());
    ck_tile::DeviceMem d_out(h_out.get_element_space_size_in_bytes());
    ck_tile::DeviceMem d_indices(h_indices.get_element_space_size_in_bytes());
    ck_tile::DeviceMem d_dout(h_dout.get_element_space_size_in_bytes());
    ck_tile::DeviceMem d_din(h_din.get_element_space_size_in_bytes());

    d_in.ToDevice(h_in.data());
    d_dout.ToDevice(h_dout.data());

    const auto input_shape   = ck_tile::make_tuple(N_, D_, H_, W_, C_);
    const auto output_shape  = ck_tile::make_tuple(N_, Do_, Ho_, Wo_, C_);
    const auto input_strides = ck_tile::make_tuple(D_ * H_ * W_ * C_, H_ * W_ * C_, W_ * C_, C_, 1);
    const auto output_strides =
        ck_tile::make_tuple(Do_ * Ho_ * Wo_ * C_, Ho_ * Wo_ * C_, Wo_ * C_, C_, 1);
    const auto window_lengths = ck_tile::make_tuple(Z_, Y_, X_);
    const auto window_strides = ck_tile::make_tuple(stride_d_, stride_h_, stride_w_);
    const auto window_dils    = ck_tile::make_tuple(dilation_d_, dilation_h_, dilation_w_);
    const auto left_pads      = ck_tile::make_tuple(pad_d_left_, pad_h_left_, pad_w_left_);
    const auto right_pads     = ck_tile::make_tuple(pad_d_right_, pad_h_right_, pad_w_right_);

    using ReduceOp   = ck_tile::ReduceOp::Max;
    using BlockWarps = ck_tile::sequence<1, 1>;
    using BlockTile  = ck_tile::sequence<128, 1>;
    using WarpTile   = ck_tile::sequence<128, 1>;
    using ThreadTile = ck_tile::sequence<2, 1>;
    using FwdShape   = ck_tile::PoolShape<BlockWarps, BlockTile, WarpTile, ThreadTile>;
    using FwdProblem = ck_tile::PoolProblem<InDataType,
                                            OutDataType,
                                            ComputeDataType,
                                            IndexDataType,
                                            ReduceOp,
                                            true,
                                            false,
                                            FwdShape>;
    using FwdKernel  = ck_tile::PoolKernel<FwdProblem>;

    auto fwd_host_args = ck_tile::PoolHostArgs<decltype(input_shape), decltype(window_lengths)>{
        d_in.GetDeviceBuffer(),
        d_out.GetDeviceBuffer(),
        d_indices.GetDeviceBuffer(),
        input_shape,
        output_shape,
        input_strides,
        output_strides,
        window_lengths,
        window_strides,
        window_dils,
        left_pads,
        right_pads};
    auto fwd_kargs = FwdKernel::MakeKernelArgs(fwd_host_args);

    if(!FwdKernel::IsSupportedArgument(fwd_kargs))
    {
        GTEST_SKIP() << "Forward pool arguments not supported.";
    }

    constexpr ck_tile::index_t kFwdBlockPerCu = 1;
    const ck_tile::index_t fwd_grid_size      = FwdKernel::CalculateGridSize(fwd_kargs);
    const ck_tile::index_t fwd_block_size     = FwdKernel::BlockSize();

    ck_tile::launch_kernel(ck_tile::stream_config{nullptr, false, 0},
                           ck_tile::make_kernel<kFwdBlockPerCu>(
                               FwdKernel{}, fwd_grid_size, fwd_block_size, 0, fwd_kargs));

    const ck_tile::long_index_t din_length =
        static_cast<ck_tile::long_index_t>(h_din.get_element_space_size());
    const ck_tile::long_index_t dout_length =
        static_cast<ck_tile::long_index_t>(h_dout.get_element_space_size());

    const std::size_t workspace_bytes = SelectedKernel::BwdKernel::GetWorkSpaceSize(
        ck_tile::PoolBwdHostArgs{
            nullptr, nullptr, nullptr, nullptr, dout_length, din_length, problem_overlap});
    ck_tile::DeviceMem d_workspace(workspace_bytes);

    ck_tile::PoolBwdHostArgs bwd_host_args{d_dout.GetDeviceBuffer(),
                                           d_indices.GetDeviceBuffer(),
                                           d_din.GetDeviceBuffer(),
                                           workspace_bytes > 0 ? d_workspace.GetDeviceBuffer()
                                                               : nullptr,
                                           dout_length,
                                           din_length,
                                           problem_overlap};

    ck_tile::stream_config stream{nullptr, false, 0, 0, 1, false, false, 1};

    try
    {
        SelectedKernel::launch(bwd_host_args, stream);
    }
    catch(const std::exception& e)
    {
        const std::string msg(e.what());
        if(msg.find("Unsupported arguments") != std::string::npos)
        {
            GTEST_SKIP() << "Configuration not supported: " << e.what();
        }
        FAIL() << "Bwd kernel launch failed: " << e.what();
    }

    d_indices.FromDevice(h_indices.data());
    d_din.FromDevice(h_din.data());

    ck_tile::reference_pool_bwd<DOutDataType, IndexDataType, ComputeDataType, DInDataType>(
        h_dout, h_indices, h_din_ref);

    const bool pass = ck_tile::check_err(
        h_din, h_din_ref, "Error: Incorrect dx", pool_bwd_rtol_for_dtype(), pool_bwd_atol_for_dtype());
    EXPECT_TRUE(pass) << "Pooling bwd 3D verification failed for " << KERNEL_NAME;
}

INSTANTIATE_TEST_SUITE_P(PoolingBwdVerification,
                         PoolingBwdTileEngineTest3D,
                         ::testing::ValuesIn(CONFIG_TEST_PARAMS),
                         [](const ::testing::TestParamInfo<PoolBwdTestParams3D>& param_info) {
                             return "N" + std::to_string(param_info.param.N) + "_D" +
                                    std::to_string(param_info.param.D) + "_H" +
                                    std::to_string(param_info.param.H) + "_W" +
                                    std::to_string(param_info.param.W) + "_C" +
                                    std::to_string(param_info.param.C) + "_Z" +
                                    std::to_string(param_info.param.Z) + "_Y" +
                                    std::to_string(param_info.param.Y) + "_X" +
                                    std::to_string(param_info.param.X);
                         });

#else
#error "POOLING_BWD_DIM_VALUE must be 2 or 3"
#endif
