// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_LAYERNORMBACKWARDATTRIBUTES_HIPDNN_FLATBUFFERS_SDK_DATA_OBJECTS_H_
#define FLATBUFFERS_GENERATED_LAYERNORMBACKWARDATTRIBUTES_HIPDNN_FLATBUFFERS_SDK_DATA_OBJECTS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

#include "norm_common_generated.h"

namespace hipdnn_flatbuffers_sdk {
namespace data_objects {

struct LayernormBackwardAttributes;
struct LayernormBackwardAttributesBuilder;
struct LayernormBackwardAttributesT;

bool operator==(const LayernormBackwardAttributesT &lhs, const LayernormBackwardAttributesT &rhs);
bool operator!=(const LayernormBackwardAttributesT &lhs, const LayernormBackwardAttributesT &rhs);

struct LayernormBackwardAttributesT : public ::flatbuffers::NativeTable {
  typedef LayernormBackwardAttributes TableType;
  int64_t dy_tensor_uid = 0;
  int64_t x_tensor_uid = 0;
  ::flatbuffers::Optional<int64_t> scale_tensor_uid = ::flatbuffers::nullopt;
  ::flatbuffers::Optional<int64_t> mean_tensor_uid = ::flatbuffers::nullopt;
  ::flatbuffers::Optional<int64_t> inv_variance_tensor_uid = ::flatbuffers::nullopt;
  int64_t dx_tensor_uid = 0;
  int64_t normalized_dim_count = 0;
  hipdnn_flatbuffers_sdk::data_objects::NormFwdPhase forward_phase = hipdnn_flatbuffers_sdk::data_objects::NormFwdPhase::NOT_SET;
};

struct LayernormBackwardAttributes FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LayernormBackwardAttributesT NativeTableType;
  typedef LayernormBackwardAttributesBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DY_TENSOR_UID = 4,
    VT_X_TENSOR_UID = 6,
    VT_SCALE_TENSOR_UID = 8,
    VT_MEAN_TENSOR_UID = 10,
    VT_INV_VARIANCE_TENSOR_UID = 12,
    VT_DX_TENSOR_UID = 14,
    VT_NORMALIZED_DIM_COUNT = 16,
    VT_FORWARD_PHASE = 18
  };
  int64_t dy_tensor_uid() const {
    return GetField<int64_t>(VT_DY_TENSOR_UID, 0);
  }
  bool mutate_dy_tensor_uid(int64_t _dy_tensor_uid = 0) {
    return SetField<int64_t>(VT_DY_TENSOR_UID, _dy_tensor_uid, 0);
  }
  int64_t x_tensor_uid() const {
    return GetField<int64_t>(VT_X_TENSOR_UID, 0);
  }
  bool mutate_x_tensor_uid(int64_t _x_tensor_uid = 0) {
    return SetField<int64_t>(VT_X_TENSOR_UID, _x_tensor_uid, 0);
  }
  ::flatbuffers::Optional<int64_t> scale_tensor_uid() const {
    return GetOptional<int64_t, int64_t>(VT_SCALE_TENSOR_UID);
  }
  bool mutate_scale_tensor_uid(int64_t _scale_tensor_uid) {
    return SetField<int64_t>(VT_SCALE_TENSOR_UID, _scale_tensor_uid);
  }
  ::flatbuffers::Optional<int64_t> mean_tensor_uid() const {
    return GetOptional<int64_t, int64_t>(VT_MEAN_TENSOR_UID);
  }
  bool mutate_mean_tensor_uid(int64_t _mean_tensor_uid) {
    return SetField<int64_t>(VT_MEAN_TENSOR_UID, _mean_tensor_uid);
  }
  ::flatbuffers::Optional<int64_t> inv_variance_tensor_uid() const {
    return GetOptional<int64_t, int64_t>(VT_INV_VARIANCE_TENSOR_UID);
  }
  bool mutate_inv_variance_tensor_uid(int64_t _inv_variance_tensor_uid) {
    return SetField<int64_t>(VT_INV_VARIANCE_TENSOR_UID, _inv_variance_tensor_uid);
  }
  int64_t dx_tensor_uid() const {
    return GetField<int64_t>(VT_DX_TENSOR_UID, 0);
  }
  bool mutate_dx_tensor_uid(int64_t _dx_tensor_uid = 0) {
    return SetField<int64_t>(VT_DX_TENSOR_UID, _dx_tensor_uid, 0);
  }
  int64_t normalized_dim_count() const {
    return GetField<int64_t>(VT_NORMALIZED_DIM_COUNT, 0);
  }
  bool mutate_normalized_dim_count(int64_t _normalized_dim_count = 0) {
    return SetField<int64_t>(VT_NORMALIZED_DIM_COUNT, _normalized_dim_count, 0);
  }
  hipdnn_flatbuffers_sdk::data_objects::NormFwdPhase forward_phase() const {
    return static_cast<hipdnn_flatbuffers_sdk::data_objects::NormFwdPhase>(GetField<int8_t>(VT_FORWARD_PHASE, 0));
  }
  bool mutate_forward_phase(hipdnn_flatbuffers_sdk::data_objects::NormFwdPhase _forward_phase = static_cast<hipdnn_flatbuffers_sdk::data_objects::NormFwdPhase>(0)) {
    return SetField<int8_t>(VT_FORWARD_PHASE, static_cast<int8_t>(_forward_phase), 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_DY_TENSOR_UID, 8) &&
           VerifyField<int64_t>(verifier, VT_X_TENSOR_UID, 8) &&
           VerifyField<int64_t>(verifier, VT_SCALE_TENSOR_UID, 8) &&
           VerifyField<int64_t>(verifier, VT_MEAN_TENSOR_UID, 8) &&
           VerifyField<int64_t>(verifier, VT_INV_VARIANCE_TENSOR_UID, 8) &&
           VerifyField<int64_t>(verifier, VT_DX_TENSOR_UID, 8) &&
           VerifyField<int64_t>(verifier, VT_NORMALIZED_DIM_COUNT, 8) &&
           VerifyField<int8_t>(verifier, VT_FORWARD_PHASE, 1) &&
           verifier.EndTable();
  }
  LayernormBackwardAttributesT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(LayernormBackwardAttributesT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<LayernormBackwardAttributes> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const LayernormBackwardAttributesT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct LayernormBackwardAttributesBuilder {
  typedef LayernormBackwardAttributes Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_dy_tensor_uid(int64_t dy_tensor_uid) {
    fbb_.AddElement<int64_t>(LayernormBackwardAttributes::VT_DY_TENSOR_UID, dy_tensor_uid, 0);
  }
  void add_x_tensor_uid(int64_t x_tensor_uid) {
    fbb_.AddElement<int64_t>(LayernormBackwardAttributes::VT_X_TENSOR_UID, x_tensor_uid, 0);
  }
  void add_scale_tensor_uid(int64_t scale_tensor_uid) {
    fbb_.AddElement<int64_t>(LayernormBackwardAttributes::VT_SCALE_TENSOR_UID, scale_tensor_uid);
  }
  void add_mean_tensor_uid(int64_t mean_tensor_uid) {
    fbb_.AddElement<int64_t>(LayernormBackwardAttributes::VT_MEAN_TENSOR_UID, mean_tensor_uid);
  }
  void add_inv_variance_tensor_uid(int64_t inv_variance_tensor_uid) {
    fbb_.AddElement<int64_t>(LayernormBackwardAttributes::VT_INV_VARIANCE_TENSOR_UID, inv_variance_tensor_uid);
  }
  void add_dx_tensor_uid(int64_t dx_tensor_uid) {
    fbb_.AddElement<int64_t>(LayernormBackwardAttributes::VT_DX_TENSOR_UID, dx_tensor_uid, 0);
  }
  void add_normalized_dim_count(int64_t normalized_dim_count) {
    fbb_.AddElement<int64_t>(LayernormBackwardAttributes::VT_NORMALIZED_DIM_COUNT, normalized_dim_count, 0);
  }
  void add_forward_phase(hipdnn_flatbuffers_sdk::data_objects::NormFwdPhase forward_phase) {
    fbb_.AddElement<int8_t>(LayernormBackwardAttributes::VT_FORWARD_PHASE, static_cast<int8_t>(forward_phase), 0);
  }
  explicit LayernormBackwardAttributesBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LayernormBackwardAttributes> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LayernormBackwardAttributes>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LayernormBackwardAttributes> CreateLayernormBackwardAttributes(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t dy_tensor_uid = 0,
    int64_t x_tensor_uid = 0,
    ::flatbuffers::Optional<int64_t> scale_tensor_uid = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<int64_t> mean_tensor_uid = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<int64_t> inv_variance_tensor_uid = ::flatbuffers::nullopt,
    int64_t dx_tensor_uid = 0,
    int64_t normalized_dim_count = 0,
    hipdnn_flatbuffers_sdk::data_objects::NormFwdPhase forward_phase = hipdnn_flatbuffers_sdk::data_objects::NormFwdPhase::NOT_SET) {
  LayernormBackwardAttributesBuilder builder_(_fbb);
  builder_.add_normalized_dim_count(normalized_dim_count);
  builder_.add_dx_tensor_uid(dx_tensor_uid);
  if(inv_variance_tensor_uid) { builder_.add_inv_variance_tensor_uid(*inv_variance_tensor_uid); }
  if(mean_tensor_uid) { builder_.add_mean_tensor_uid(*mean_tensor_uid); }
  if(scale_tensor_uid) { builder_.add_scale_tensor_uid(*scale_tensor_uid); }
  builder_.add_x_tensor_uid(x_tensor_uid);
  builder_.add_dy_tensor_uid(dy_tensor_uid);
  builder_.add_forward_phase(forward_phase);
  return builder_.Finish();
}

::flatbuffers::Offset<LayernormBackwardAttributes> CreateLayernormBackwardAttributes(::flatbuffers::FlatBufferBuilder &_fbb, const LayernormBackwardAttributesT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);


inline bool operator==(const LayernormBackwardAttributesT &lhs, const LayernormBackwardAttributesT &rhs) {
  return
      (lhs.dy_tensor_uid == rhs.dy_tensor_uid) &&
      (lhs.x_tensor_uid == rhs.x_tensor_uid) &&
      (lhs.scale_tensor_uid == rhs.scale_tensor_uid) &&
      (lhs.mean_tensor_uid == rhs.mean_tensor_uid) &&
      (lhs.inv_variance_tensor_uid == rhs.inv_variance_tensor_uid) &&
      (lhs.dx_tensor_uid == rhs.dx_tensor_uid) &&
      (lhs.normalized_dim_count == rhs.normalized_dim_count) &&
      (lhs.forward_phase == rhs.forward_phase);
}

inline bool operator!=(const LayernormBackwardAttributesT &lhs, const LayernormBackwardAttributesT &rhs) {
    return !(lhs == rhs);
}


inline LayernormBackwardAttributesT *LayernormBackwardAttributes::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<LayernormBackwardAttributesT>(new LayernormBackwardAttributesT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void LayernormBackwardAttributes::UnPackTo(LayernormBackwardAttributesT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = dy_tensor_uid(); _o->dy_tensor_uid = _e; }
  { auto _e = x_tensor_uid(); _o->x_tensor_uid = _e; }
  { auto _e = scale_tensor_uid(); _o->scale_tensor_uid = _e; }
  { auto _e = mean_tensor_uid(); _o->mean_tensor_uid = _e; }
  { auto _e = inv_variance_tensor_uid(); _o->inv_variance_tensor_uid = _e; }
  { auto _e = dx_tensor_uid(); _o->dx_tensor_uid = _e; }
  { auto _e = normalized_dim_count(); _o->normalized_dim_count = _e; }
  { auto _e = forward_phase(); _o->forward_phase = _e; }
}

inline ::flatbuffers::Offset<LayernormBackwardAttributes> LayernormBackwardAttributes::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const LayernormBackwardAttributesT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateLayernormBackwardAttributes(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<LayernormBackwardAttributes> CreateLayernormBackwardAttributes(::flatbuffers::FlatBufferBuilder &_fbb, const LayernormBackwardAttributesT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const LayernormBackwardAttributesT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _dy_tensor_uid = _o->dy_tensor_uid;
  auto _x_tensor_uid = _o->x_tensor_uid;
  auto _scale_tensor_uid = _o->scale_tensor_uid;
  auto _mean_tensor_uid = _o->mean_tensor_uid;
  auto _inv_variance_tensor_uid = _o->inv_variance_tensor_uid;
  auto _dx_tensor_uid = _o->dx_tensor_uid;
  auto _normalized_dim_count = _o->normalized_dim_count;
  auto _forward_phase = _o->forward_phase;
  return hipdnn_flatbuffers_sdk::data_objects::CreateLayernormBackwardAttributes(
      _fbb,
      _dy_tensor_uid,
      _x_tensor_uid,
      _scale_tensor_uid,
      _mean_tensor_uid,
      _inv_variance_tensor_uid,
      _dx_tensor_uid,
      _normalized_dim_count,
      _forward_phase);
}

}  // namespace data_objects
}  // namespace hipdnn_flatbuffers_sdk

#endif  // FLATBUFFERS_GENERATED_LAYERNORMBACKWARDATTRIBUTES_HIPDNN_FLATBUFFERS_SDK_DATA_OBJECTS_H_
