// Copyright (c) Advanced Micro Devices, Inc., or its affiliates.
// SPDX-License-Identifier: MIT

#include "ck/host/device_fmha_fwd/problem.hpp"
#include "ck/host/device_fmha_fwd/operation.hpp"
#include <algorithm>

namespace ck {
namespace host {
namespace device_fmha_fwd {

// Based on factories defined in fmha_fwd.py
// Phase 7 unblocked gfx9 (incl. gfx950). Phase 8 adds gfx11 and gfx12.
// Every supported arch has an entry in fmha_arch_specs.json and thus
// an autogenerated tile table; pipeline configs come from the
// arch-specific GetPipelinesGfx* helpers below.
bool IsSupportedArch(const std::string& arch)
{
    if(arch.find("gfx9") == 0)  return true;   // gfx90a, gfx942, gfx950, gfx908, gfx9_4_generic
    if(arch.find("gfx12") == 0) return true;   // gfx1200, gfx1201, gfx12_generic (Phase 8)
    if(arch.find("gfx11") == 0) return true;   // gfx1100, gfx1101, gfx11_generic (Phase 8)
    return false;
}

std::string Problem::GetIncludeHeader() const
{
    return "ck/host/device_fmha_fwd/fmha_fwd_wrapper.hpp";
}

std::vector<Solution> Problem::GetSolutions(const std::string& arch) const
{
    if(!IsSupportedArch(arch))
        return {};

    auto ops = Operation::CreateOperations(*this, arch);
    std::vector<Solution> result;
    std::transform(ops.begin(), ops.end(), std::back_inserter(result), [](const auto& op) {
        return op.ToSolution();
    });
    return result;
}

} // namespace device_fmha_fwd
} // namespace host
} // namespace ck
