// Copyright (c) Advanced Micro Devices, Inc., or its affiliates.
// SPDX-License-Identifier: MIT

#include "ck/host/device_fmha_fwd/operation.hpp"
#include "ck/host/device_fmha_fwd/problem.hpp"
#include "ck/host/stringutils.hpp"
#include <algorithm>
#include <cstddef>
#include <map>
#include <string>
#include <vector>

namespace ck {
namespace host {
namespace device_fmha_fwd {

static const char* const FmhaFwdWrapperTemplate =
    "ck_tile::FmhaFwdWrapper<${DataType}, "
    "${BM0}, ${BN0}, ${BK0}, ${BN1}, ${BK1}, ${BK0Max}, "
    "${RM0}, ${RN0}, ${RK0}, ${RM1}, ${RN1}, ${RK1}, "
    "${WM0}, ${WN0}, ${WK0}, ${WM1}, ${WN1}, ${WK1}, "
    "${IsCausal}, ${IsVRowMajor}, ${HasBias}, "
    "${PadM}, ${PadN}, ${PadK}, ${PadO}, "
    "ck_tile::FmhaPipelineTag::${PipelineTag}>";

static bool IsGfx950(const std::string& arch) { return arch.find("gfx950") == 0; }
static bool IsGfx12(const std::string& arch) { return arch.find("gfx12") == 0; }

// TileMap is now declared in operation.hpp (Phase 4). The autogenerated
// tile tables under build/generated_tile_tables/ also use this type.

// gfx9 fp16/bf16 tile configurations
//
// Constraints that must be satisfied:
//   - rn0 = rk0 = rn1 = rk1 = 1 (only M-dimension warp distribution supported)
//   - rm0 == rm1 (BlockGemm requires identical thread buffer sizes between GEMM0/GEMM1)
//   - bk0max >= 2 * bk0 (k0_loops >= 2 required for correct pipelining)
//   - bk0 >= wk0 (block K must be at least warp K; for fp16 min wk0 is 16)
//   - bn1 = hdim_v (output head dimension processed per block)
//   - bk1 = 32 (fixed for softmax/attention score reduction pipelining)
//   - (wm0, wn0, wk0) and (wm1, wn1, wk1) must be valid MFMA sizes for the dtype
//   - rm0=8 not supported when bn1 is not power-of-2 (V tensor distribution alignment)
//
// Valid fp16 MFMA sizes: (32,32,16), (16,16,16), (16,16,32), (4,64,16), (64,4,16)
// However, not all are usable in this kernel:
//   - (64,4,16), (4,64,16): warp_gemm_dispatcher has no template specialization
//   - (32,32,8): produces invalid results (likely internal kernel issue)
//   - (16,16,32): requires bk0 >= 2*wk0 (bk0 >= 64), only usable when bk0max >= 128
//
// clang-format off
static const TileMap gfx9_fp16_tiles = {
    //             bm0, bn0, bk0, bn1, bk1,bk0max,rm0,rn0,rk0,rm1,rn1,rk1, wm0,wn0,wk0, wm1,wn1,wk1
    {{32, 32},   {{128,  64,  16,  32,  32,  32,   4,  1,  1,   4,  1,  1,  32, 32, 16,  32, 32, 16},
                  { 64,  64,  16,  32,  32,  32,   4,  1,  1,   4,  1,  1,  16, 16, 16,  16, 16, 16},
                  { 64,  64,  16,  32,  32,  32,   2,  1,  1,   2,  1,  1,  32, 32, 16,  32, 32, 16},
                  { 32,  64,  16,  32,  32,  32,   2,  1,  1,   2,  1,  1,  16, 16, 16,  16, 16, 16},
                  { 16,  32,  16,  32,  32,  32,   1,  1,  1,   1,  1,  1,  16, 16, 16,  16, 16, 16},
                  {128,  64,  16,  32,  32,  32,   8,  1,  1,   8,  1,  1,  16, 16, 16,  16, 16, 16}}},

    {{64, 64},   {{128,  64,  32,  64,  32,  64,   4,  1,  1,   4,  1,  1,  32, 32, 16,  32, 32, 16},
                  { 64,  64,  32,  64,  32,  64,   2,  1,  1,   2,  1,  1,  32, 32, 16,  32, 32, 16},
                  { 32,  64,  32,  64,  32,  64,   2,  1,  1,   2,  1,  1,  16, 16, 16,  16, 16, 16},
                  { 64,  64,  32,  64,  32,  64,   4,  1,  1,   4,  1,  1,  16, 16, 16,  16, 16, 16},
                  {128,  64,  32,  64,  32,  64,   8,  1,  1,   8,  1,  1,  16, 16, 16,  16, 16, 16},
                  { 16,  64,  32,  64,  32,  64,   1,  1,  1,   1,  1,  1,  16, 16, 16,  16, 16, 16}}},

    {{80, 96},   {{128, 128,  16,  96,  32,  80,   4,  1,  1,   4,  1,  1,  32, 32, 16,  32, 32, 16},
                  { 16, 128,  16,  96,  32,  80,   1,  1,  1,   1,  1,  1,  16, 16, 16,  16, 16, 16},
                  { 32, 128,  16,  96,  32,  80,   2,  1,  1,   2,  1,  1,  16, 16, 16,  16, 16, 16},
                  { 64, 128,  16,  96,  32,  80,   2,  1,  1,   2,  1,  1,  32, 32, 16,  32, 32, 16},
                  { 64, 128,  16,  96,  32,  80,   4,  1,  1,   4,  1,  1,  16, 16, 16,  16, 16, 16}}},

    {{96, 128},  {{128, 128,  32, 128,  32,  96,   4,  1,  1,   4,  1,  1,  32, 32, 16,  32, 32, 16},
                  { 16, 128,  32, 128,  32,  96,   1,  1,  1,   1,  1,  1,  16, 16, 16,  16, 16, 16},
                  { 32, 128,  32, 128,  32,  96,   2,  1,  1,   2,  1,  1,  16, 16, 16,  16, 16, 16},
                  { 64, 128,  32, 128,  32,  96,   2,  1,  1,   2,  1,  1,  32, 32, 16,  32, 32, 16},
                  { 64, 128,  32, 128,  32,  96,   4,  1,  1,   4,  1,  1,  16, 16, 16,  16, 16, 16},
                  {128, 128,  32, 128,  32,  96,   8,  1,  1,   8,  1,  1,  16, 16, 16,  16, 16, 16}}},

    {{128, 128}, {{ 64, 128,  32, 128,  32, 128,   4,  1,  1,   4,  1,  1,  16, 16, 32,  16, 16, 16},
                  {128,  64,  32, 128,  16, 128,   4,  1,  1,   4,  1,  1,  32, 32, 16,  32, 32, 16},
                  {128, 128,  32, 128,  32, 128,   4,  1,  1,   4,  1,  1,  32, 32, 16,  32, 32, 16},
                  { 32, 128,  32, 128,  32, 128,   2,  1,  1,   2,  1,  1,  16, 16, 16,  16, 16, 16},
                  { 64, 128,  32, 128,  32, 128,   4,  1,  1,   4,  1,  1,  16, 16, 16,  16, 16, 16},
                  {128, 128,  32, 128,  32, 128,   8,  1,  1,   8,  1,  1,  16, 16, 16,  16, 16, 16},
                  { 64, 128,  32, 128,  32, 128,   2,  1,  1,   2,  1,  1,  32, 32, 16,  32, 32, 16},
                  { 32, 128,  64, 128,  32, 128,   2,  1,  1,   2,  1,  1,  16, 16, 32,  16, 16, 16},
                  { 64, 128,  64, 128,  32, 128,   4,  1,  1,   4,  1,  1,  16, 16, 32,  16, 16, 16},
                  {128, 128,  64, 128,  32, 128,   8,  1,  1,   8,  1,  1,  16, 16, 32,  16, 16, 16}}},

    {{192, 128}, {{128, 128,  32, 128,  32, 192,   4,  1,  1,   4,  1,  1,  32, 32, 16,  32, 32, 16},
                  { 64, 128,  32, 128,  32, 192,   4,  1,  1,   4,  1,  1,  16, 16, 32,  16, 16, 16},
                  { 16, 128,  32, 128,  32, 192,   1,  1,  1,   1,  1,  1,  16, 16, 16,  16, 16, 16},
                  { 32, 128,  32, 128,  32, 192,   2,  1,  1,   2,  1,  1,  16, 16, 16,  16, 16, 16},
                  { 64, 128,  32, 128,  32, 192,   4,  1,  1,   4,  1,  1,  16, 16, 16,  16, 16, 16},
                  {128, 128,  32, 128,  32, 192,   8,  1,  1,   8,  1,  1,  16, 16, 16,  16, 16, 16},
                  { 64, 128,  32, 128,  32, 192,   2,  1,  1,   2,  1,  1,  32, 32, 16,  32, 32, 16},
                  {256, 128,  32, 128,  32, 192,   8,  1,  1,   8,  1,  1,  32, 32, 16,  32, 32, 16},
                  { 32, 128,  32, 128,  32, 192,   2,  1,  1,   2,  1,  1,  16, 16, 32,  16, 16, 16},
                  {128, 128,  32, 128,  32, 192,   8,  1,  1,   8,  1,  1,  16, 16, 32,  16, 16, 16},
                  { 32, 128,  64, 128,  32, 192,   2,  1,  1,   2,  1,  1,  16, 16, 32,  16, 16, 16},
                  { 64, 128,  64, 128,  32, 192,   4,  1,  1,   4,  1,  1,  16, 16, 32,  16, 16, 16},
                  {128, 128,  64, 128,  32, 192,   8,  1,  1,   8,  1,  1,  16, 16, 32,  16, 16, 16}}},

    {{192, 192}, {{128, 128,  32, 192,  32, 192,   4,  1,  1,   4,  1,  1,  32, 32, 16,  32, 32, 16},
                  { 64, 128,  32, 192,  32, 192,   2,  1,  1,   2,  1,  1,  32, 32, 16,  32, 32, 16},
                  {256, 128,  32, 192,  32, 192,   8,  1,  1,   8,  1,  1,  32, 32, 16,  32, 32, 16},
                  { 16, 128,  32, 192,  32, 192,   1,  1,  1,   1,  1,  1,  16, 16, 16,  16, 16, 16},
                  { 32, 128,  32, 192,  32, 192,   2,  1,  1,   2,  1,  1,  16, 16, 16,  16, 16, 16},
                  { 64, 128,  32, 192,  32, 192,   4,  1,  1,   4,  1,  1,  16, 16, 16,  16, 16, 16},
                  {128, 128,  32, 192,  32, 192,   8,  1,  1,   8,  1,  1,  16, 16, 16,  16, 16, 16},
                  { 32, 128,  32, 192,  32, 192,   2,  1,  1,   2,  1,  1,  16, 16, 32,  16, 16, 16},
                  {128, 128,  32, 192,  32, 192,   8,  1,  1,   8,  1,  1,  16, 16, 32,  16, 16, 16}}},

    {{256, 256}, {{128, 128,  32, 256,  32, 256,   4,  1,  1,   4,  1,  1,  32, 32, 16,  32, 32, 16},
                  { 64, 128,  32, 256,  32, 256,   2,  1,  1,   2,  1,  1,  32, 32, 16,  32, 32, 16},
                  {256, 128,  32, 256,  32, 256,   8,  1,  1,   8,  1,  1,  32, 32, 16,  32, 32, 16},
                  { 16, 128,  32, 256,  32, 256,   1,  1,  1,   1,  1,  1,  16, 16, 16,  16, 16, 16},
                  { 32, 128,  32, 256,  32, 256,   2,  1,  1,   2,  1,  1,  16, 16, 16,  16, 16, 16},
                  { 64, 128,  32, 256,  32, 256,   4,  1,  1,   4,  1,  1,  16, 16, 16,  16, 16, 16},
                  {128, 128,  32, 256,  32, 256,   8,  1,  1,   8,  1,  1,  16, 16, 16,  16, 16, 16},
                  { 32, 128,  32, 256,  32, 256,   2,  1,  1,   2,  1,  1,  16, 16, 32,  16, 16, 16},
                  {128, 128,  32, 256,  32, 256,   8,  1,  1,   8,  1,  1,  16, 16, 32,  16, 16, 16}}},
};

// TODO WIP - Currently not used, additional configs will be added later
// gfx12 fp16/bf16 tiles from KernelComponentFactoryGfx12::get_hdim_tile_size_dict
static const TileMap gfx12_fp16_tiles = {
    //             bm0, bn0, bk0, bn1, bk1,bk0max,rm0,rn0,rk0,rm1,rn1,rk1, wm0,wn0,wk0, wm1,wn1,wk1
    {{32, 32},   {{ 64,  64,  16,  32,  32,  32,   4,  1,  1,   4,  1,  1,  16, 16, 16,  16, 16, 16}}},
    {{64, 64},   {{ 64,  64,  32,  64,  32,  64,   4,  1,  1,   4,  1,  1,  16, 16, 16,  16, 16, 16}}},
    {{128, 128}, {{ 64,  64,  32, 128,  32, 128,   4,  1,  1,   4,  1,  1,  16, 16, 16,  16, 16, 16}}},
    {{192, 128}, {{ 64,  64,  32, 128,  32, 256,   4,  1,  1,   4,  1,  1,  16, 16, 16,  16, 16, 16}}},
    {{256, 256}, {{ 64,  64,  32, 256,  32, 256,   4,  1,  1,   4,  1,  1,  16, 16, 16,  16, 16, 16}}},
};
// clang-format on

// Forward-declared by the autogenerated tile_tables_registry.cpp (Phase 4).
namespace generated {
HdimBucketResult lookup_generated(const std::string& arch,
                                  const std::string& dtype_name,
                                  std::size_t K,
                                  std::size_t O);
} // namespace generated

// Map the Solution-level DataType enum onto the string that the
// autogenerated tables are keyed by. Phase 2 hard-mapped everything to
// fp16; Phase 4 widens this once the expanded DataType enum lands.
// Keep the conservative mapping until then: only Half and Float are
// valid Solution dtypes today, and we route them to fp16/fp32.
static const char* dtype_to_generated_name(DataType dtype)
{
    switch(dtype)
    {
    case DataType::Half:  return "fp16";
    case DataType::Float: return "fp32";
    default:              return "fp16";
    }
}

HdimBucketResult
GetTileConfigsForHdim(const std::string& arch, DataType dtype, std::size_t K, std::size_t O)
{
    HdimBucketResult result;

    // Prefer MGX's hand-rolled fp16 tables first for gfx9 and gfx12 --
    // they carry richer per-bucket variants than the autogenerated
    // single-entry tables from fmha_arch_specs.json. For gfx11 and other
    // arches, skip MGX curation and use the Phase 4 autogenerated path.
    const bool use_mgx_fp16 =
        (dtype == DataType::Half) && (IsGfx12(arch) || arch.find("gfx9") == 0);
    if(use_mgx_fp16)
    {
        const TileMap& tile_map = IsGfx12(arch) ? gfx12_fp16_tiles : gfx9_fp16_tiles;
        for(const auto& [key, tiles] : tile_map)
        {
            if(K <= key.first && O <= key.second)
            {
                result.bucket_hdim   = key.first;
                result.bucket_hdim_v = key.second;
                result.tiles         = tiles;
                return result;
            }
        }
    }

    // Phase 4 fallback: autogenerated tables from fmha_arch_specs.json.
    // Covers every (arch, dtype) pair that MGX didn't hand-curate:
    // bf16/fp8/bf8 everywhere, gfx950 extras, gfx11 / gfx12 for every
    // dtype present in the JSON. Single-tile-per-bucket (safe default
    // wave/warp), so coverage is broad but not necessarily optimal;
    // curated expansions live in the MGX table above when they exist.
    return generated::lookup_generated(arch, dtype_to_generated_name(dtype), K, O);
}

static bool IsGfx11(const std::string& arch) { return arch.find("gfx11") == 0; }

static std::vector<PipelineConfig> GetPipelinesGfx12(bool has_bias)
{
    // Phase 8: gfx12 (RDNA4) pipelines. qr_nwarp_sshuffle is the RDNA
    // warp-level shuffle-based accumulation pipeline. Available for
    // fp16/bf16/fp8/fp8bf16 on gfx12.
    std::vector<PipelineConfig> configs;
    if(!has_bias)
    {
        configs.push_back({"qr_nwarp_sshuffle", true, false, true, true});
        configs.push_back({"qr_nwarp_sshuffle", true, true,  true, true});
    }
    return configs;
}

static std::vector<PipelineConfig> GetPipelinesGfx11(bool has_bias)
{
    // Phase 8: gfx11 (RDNA3) pipelines. Subset of gfx12 configs
    // (no fp8 support on gfx11).
    std::vector<PipelineConfig> configs;
    if(!has_bias)
    {
        configs.push_back({"qr_nwarp_sshuffle", true, false, true, true});
        configs.push_back({"qr_nwarp_sshuffle", true, true,  true, true});
    }
    return configs;
}

static std::vector<PipelineConfig>
GetPipelinesGfx9(std::size_t bucket_hdim, std::size_t bucket_hdim_v, bool has_bias)
{
    // QR pipeline is handled separately in CreateOperations with exact padding
    std::vector<PipelineConfig> configs;

    // QR_ASYNC pipeline requires pad_m=true, pad_k=true, pad_o=true (enforced by static_assert
    // in BlockFmhaPipelineQRKSVSAsync). Only pad_n is variable.
    if(!has_bias)
    {
        configs.push_back({"qr_async", true, false, true, true}); // pad_n=false
        configs.push_back({"qr_async", true, true, true, true});  // pad_n=true
    }

    // Note: qr_async_trload requires gfx950+ (uses buffer_load_dwordx3/x4 instructions)

    return configs;
}

// Phase 7: populated gfx950 pipeline configs. Adds qr_async_trload,
// v3, and qr_async_trload_v3 variants on top of the gfx9 baseline.
// Tile-validity filters still live in device_fmha_fwd_operation.cpp's
// CreateOperations -- Phase 4 generation covers the tile shapes; this
// function expresses which pipelines apply per bucket.
static std::vector<PipelineConfig>
GetPipelinesGfx950(std::size_t bucket_hdim, std::size_t bucket_hdim_v, bool has_bias)
{
    auto configs = GetPipelinesGfx9(bucket_hdim, bucket_hdim_v, has_bias);

    bool is_hdim_256    = (bucket_hdim == 256 && bucket_hdim_v == 256);
    bool is_hdim_128_up = (bucket_hdim >= 128 && bucket_hdim_v >= 128);

    if(!is_hdim_256 && !has_bias)
    {
        // qr_async_trload: uses buffer_load_dwordx3/x4 intrinsics.
        configs.push_back({"qr_async_trload", true, false, true, true});
        configs.push_back({"qr_async_trload", true, true,  true, true});
    }

    // V3 pipeline family: available on gfx950 for hdim >= 128, no bias.
    // Uses BlockFmhaFwdV3Pipeline + FmhaFwdV3Kernel with different
    // tile-partitioner semantics than the default kernel template.
    if(is_hdim_128_up && !has_bias)
    {
        configs.push_back({"v3", true, false, true, true});
        configs.push_back({"qr_async_trload_v3", true, false, true, true});
    }

    return configs;
}

static std::vector<PipelineConfig> GetPipelineConfigs(const std::string& arch,
                                                      std::size_t bucket_hdim,
                                                      std::size_t bucket_hdim_v,
                                                      bool has_bias)
{
    if(IsGfx12(arch))
        return GetPipelinesGfx12(has_bias);
    if(IsGfx11(arch))
        return GetPipelinesGfx11(has_bias);
    if(IsGfx950(arch))
        return GetPipelinesGfx950(bucket_hdim, bucket_hdim_v, has_bias);
    return GetPipelinesGfx9(bucket_hdim, bucket_hdim_v, has_bias);
}

// --- Phase 12 correctness fix: V-LDS descriptor validity ---
//
// `ck_tile::BlockFmhaPipelineQXKSVSCustomPolicy::MakeVLdsBlockDescriptor`
// enforces `kNPerBlock (=BN1) % NPerRow == 0` at hipRTC compile time,
// where NPerRow = PixelsPerRow / kKPack and PixelsPerRow =
// arch_banks * 4 / sizeof(dtype). gfx950 doubles the LDS banks
// (64 vs 32), which doubles PixelsPerRow and can make a BN1 that
// was valid on gfx9 invalid on gfx950. Similarly kKPack depends on
// BN1*BK1/kBlockSize: small BN1 + small BK1 + high block-warp count
// (RM0*RM1) shrinks kKPack, which raises NPerRow, which raises the
// BN1 divisibility requirement. When that compound condition fails,
// the kernel's static_assert fires and hipRTC aborts compilation.
//
// Historical incident: MGX's hand-rolled gfx9_fp16_tiles "128/128"
// variant `(BM0=128, BN0=64, ..., BN1=32, BK1=32, RM0=8, WM0=16, WN0=16)`
// caused `kNPerBlock (32) % NPerRow (64) != 0` on gfx950 when
// test_fmha_fwd_simple_validation ran, because the gfx950 banks=64
// + kKPack=2 combination forces NPerRow=64.
//
// Fix: reject the tile *before* we emit it from CreateOperations so
// every registered Solution compiles successfully via hipRTC.
static std::size_t WarpSizeForArch(const std::string& arch)
{
    // AMD convention: CDNA uses wavefront 64, RDNA uses wavefront 32.
    if(arch.find("gfx9") == 0)  return 64; // gfx90a, gfx942, gfx950, gfx908
    if(arch.find("gfx10") == 0) return 32;
    if(arch.find("gfx11") == 0) return 32;
    if(arch.find("gfx12") == 0) return 32;
    return 64; // safe default: CDNA semantics
}

static std::size_t LdsBanksForArch(const std::string& arch)
{
    // Must mirror ck_tile::get_n_lds_banks() in
    // include/ck_tile/core/arch/arch.hpp (gfx9=32, gfx950=64, RDNA=32).
    if(arch.find("gfx950") == 0) return 64;
    return 32;
}

static std::size_t DataTypeSize(DataType dt)
{
    switch(dt)
    {
    case DataType::Half:  return 2; // fp16/bf16
    case DataType::Float: return 4;
    case DataType::Int8:  return 1;
    case DataType::Int32: return 4;
    default:              return 2;
    }
}

// Returns true when the tile config satisfies the V-LDS descriptor
// invariants for a specific (arch, dtype) combination. Mirrors
// MakeVLdsBlockDescriptor in
// block_fmha_pipeline_qx_ks_vs_custom_policy.hpp (lines 633-644).
static bool VLdsDescriptorValidFor(const TileConfig& tile,
                                   DataType dtype,
                                   const std::string& arch)
{
    const std::size_t dt_size    = DataTypeSize(dtype);
    if(dt_size == 0) return false;

    const std::size_t warp_size  = WarpSizeForArch(arch);
    const std::size_t block_size = tile.rm0 * tile.rn0 * tile.rk0 * warp_size;
    if(block_size == 0) return false;

    const std::size_t kN1 = tile.bn1;
    const std::size_t kK1 = tile.bk1;
    if(kN1 == 0 || kK1 == 0) return false;

    // GetSmemKPackV: kMaxVecLoad = min(total_pixels, 16 / sizeof(V))
    const std::size_t total_pixels = (kN1 * kK1) / block_size;
    const std::size_t vec_cap      = 16u / dt_size;
    if(total_pixels == 0 || vec_cap == 0) return false;
    const std::size_t k_pack = std::min(total_pixels, vec_cap);
    if(k_pack == 0) return false;

    // MakeVLdsBlockDescriptor: PixelsPerRow = Banks * 4 / sizeof(V);
    //                         NPerRow      = PixelsPerRow / kKPack.
    const std::size_t banks          = LdsBanksForArch(arch);
    const std::size_t pixels_per_row = (banks * 4u) / dt_size;
    if(pixels_per_row == 0) return false;
    if(pixels_per_row % k_pack != 0) return false; // static_assert PixelsPerRow % kKPack
    const std::size_t n_per_row = pixels_per_row / k_pack;
    if(n_per_row == 0) return false;

    // The load-bearing constraint: kNPerBlock % NPerRow == 0.
    if((kN1 % n_per_row) != 0) return false;

    // And the companion: kKPerBlock % kKPack == 0.
    if((kK1 % k_pack) != 0) return false;

    return true;
}

// Conservative validator used during Solution emission. Checks the
// descriptor against:
//   (a) the arch the caller explicitly requested, and
//   (b) gfx950 -- the strictest currently-known fp16 constraint
//       (banks=64 doubles NPerRow vs the banks=32 family).
//
// This keeps emitted Solutions portable across the gfx9 family, which
// matches how the MGX test cross-compiles gfx90a-selected Solutions to
// the gfx950 device via hipRTC (`rtc::get_device_name()`). The
// downstream caller can always run the per-arch variant directly if
// they want to opt out of cross-arch safety.
static bool VLdsDescriptorValid(const TileConfig& tile,
                                DataType dtype,
                                const std::string& arch)
{
    if(!VLdsDescriptorValidFor(tile, dtype, arch)) return false;

    // Only apply the cross-arch check when the selected arch is in the
    // gfx9 family -- gfx12/gfx11 already have their own autogenerated
    // tables that don't cross-compile into gfx9.
    if(arch.find("gfx9") == 0 && arch.find("gfx950") != 0)
    {
        if(!VLdsDescriptorValidFor(tile, dtype, "gfx950")) return false;
    }

    return true;
}

// --- Phase 12 correctness fix: trload K-DRAM distribution validity ---
//
// `BlockFmhaPipelineQRKSVSAsyncTrloadPolicy::MakeKDramTileDistribution`
// in block_fmha_pipeline_qr_ks_vs_async_trload_policy.hpp (lines 143-167)
// computes the K-direction global-load vector width from the tile shape:
//
//   kBlockSize    = RM0 * RN0 * RK0 * warp_size
//   ElemPerThread = (kN0 * kK0) / kBlockSize
//   K1            = min(16 / sizeof(KDataType), ElemPerThread)
//
// The emitted distribution has K1 as the innermost (contiguous) Y axis,
// which becomes `ScalarPerVector` in `tile_window_base.hpp::Traits` and
// ultimately the `N` template arg of `amd_async_buffer_load<T, N>`.
// The intrinsic static_assert `bytes == 4 || bytes == 12 || bytes == 16`
// then requires `K1 * sizeof(KDataType)` to land in that set.
//
// Historical incident: MGX's `(BM0=64, BN0=64, BK0=16, BN1=32, BK1=32,
// BK0Max=32, RM0=4, WM0=16)` with qr_async_trload produces
// ElemPerThread=4, K1=4, bytes = 4*2 = 8 which is NOT in {4,12,16}
// → intrinsic static_assert fires → hipRTC aborts.
//
// This predicate is specific to the qr_async_trload / qr_async_trload_v3
// pipelines (qx_ks_vs's own async path uses a different distribution
// that clamps KVector to arch MaxLoadSizeInBytes and is always valid).
static bool TrloadKDramVectorValid(const TileConfig& tile,
                                   DataType dtype,
                                   const std::string& arch)
{
    const std::size_t dt_size = DataTypeSize(dtype);
    if(dt_size == 0) return false;

    const std::size_t warp_size  = WarpSizeForArch(arch);
    const std::size_t block_size = tile.rm0 * tile.rn0 * tile.rk0 * warp_size;
    if(block_size == 0) return false;

    const std::size_t kN0 = tile.bn0;
    const std::size_t kK0 = tile.bk0;
    if(kN0 == 0 || kK0 == 0) return false;

    // ElemPerThread = (kN0 * kK0) / kBlockSize -- integer division as in
    // ck_tile; if the numerator is smaller than kBlockSize the result is
    // 0 which would produce K1=0 and a degenerate distribution.
    const std::size_t elem_per_thread = (kN0 * kK0) / block_size;
    if(elem_per_thread == 0) return false;

    const std::size_t max_vec   = 16u / dt_size; // MaxVectorSize
    const std::size_t k1        = std::min(max_vec, elem_per_thread);
    const std::size_t bytes_k1  = k1 * dt_size;

    // Intrinsic constraint: bytes ∈ {4, 12, 16} (dword, dwordx3, dwordx4).
    if(bytes_k1 != 4u && bytes_k1 != 12u && bytes_k1 != 16u) return false;

    // And the distribution must cleanly partition: kK0 % K1 == 0,
    // kN0 % (kBlockSize/WarpSize * WarpSize/K0) == 0.
    if((kK0 % k1) != 0) return false;
    const std::size_t k0 = kK0 / k1;
    if(k0 == 0 || warp_size % k0 != 0) return false;

    return true;
}

// --- Phase 12 correctness fix: K-LDS async-load descriptor validity ---
//
// `MakeKLdsLoadBlockDescriptor` (block_fmha_pipeline_qx_ks_vs_custom_policy.hpp
// lines 577-628) has two invariants that must hold at hipRTC compile
// time for the async-copy K-LDS path:
//
//   1. `WarpSize * KVector >= kKPerBlock && WarpSize * KVector % kKPerBlock == 0`
//      -- i.e. the warp's aggregate vector width spans at least one
//      K tile and divides evenly.
//   2. `NumIssues = kNPerBlock / (LaneGroups * NumWarps) >= 1`
//      with `LaneGroups = WarpSize / LanesPerK` and
//      `LanesPerK = kKPerBlock / KVector`.
//
// Historical incident: MGX's hand-rolled gfx9_fp16_tiles "64/64" bucket
// entry `(BM0=128, BN0=64, BK0=32, BN1=64, BK1=32, RM0=8, WM0=16)`
// produces NumIssues = 64 / ((64/4) * 8) = 64/128 = 0 which makes the
// k_lds_block_desc an empty tensor and cascades into
// `space_filling_curve: 0 < TensorSize` static_assert.
//
// This validator is specifically for async pipelines (QR_ASYNC family);
// pure QR uses a different K-LDS path.
static bool KLdsAsyncDescriptorValid(const TileConfig& tile,
                                     DataType dtype,
                                     const std::string& arch)
{
    const std::size_t dt_size    = DataTypeSize(dtype);
    if(dt_size == 0) return false;

    const std::size_t warp_size  = WarpSizeForArch(arch);

    const std::size_t kN0 = tile.bn0;
    const std::size_t kK1 = tile.bk1;
    if(kN0 == 0 || kK1 == 0) return false;

    // KVector: GetAlignmentK returns min(16/sizeof(T), kK1/<something>)
    // but for the conservative validator we use the maximum global-load
    // vector width (16B / sizeof) -- if the tile works at max vec, it'll
    // work at any smaller adaptive choice too.
    const std::size_t k_vector = 16u / dt_size;
    if(k_vector == 0) return false;

    // Line 590: WarpSize * KVector >= kKPerBlock && ... % kKPerBlock == 0
    const std::size_t warp_k = warp_size * k_vector;
    if(warp_k < kK1) return false;
    if((warp_k % kK1) != 0) return false;

    const std::size_t lanes_per_k  = kK1 / k_vector;
    if(lanes_per_k == 0) return false;
    if((warp_size % lanes_per_k) != 0) return false;

    const std::size_t lane_groups  = warp_size / lanes_per_k;
    const std::size_t num_warps    = tile.rm0 * tile.rn0 * tile.rk0;
    if(num_warps == 0) return false;

    // Line 593: NumIssues = kN0 / (LaneGroups * NumWarps) must be >= 1
    // and integer-divisible (else the emitted tuple contains a 0).
    const std::size_t denom = lane_groups * num_warps;
    if(denom == 0) return false;
    if(kN0 < denom) return false;
    if((kN0 % denom) != 0) return false;

    return true;
}

static bool IsPaddingCompatible(const PipelineConfig& config,
                                const Problem& prob,
                                const TileConfig& tile,
                                std::size_t bucket_hdim,
                                std::size_t bucket_hdim_v)
{
    bool needs_pad_m = (prob.M % tile.bm0 != 0);
    bool needs_pad_n = (prob.N % tile.bn0 != 0);
    bool needs_pad_k = (prob.K != bucket_hdim);
    bool needs_pad_o = (prob.O != bucket_hdim_v);

    // +------------+----------+------------+
    // | config.pad | needs_pad| compatible |
    // +------------+----------+------------+
    // |   false    |  false   |    true    |
    // |   false    |  true    |    false   |
    // |   true     |  false   |    true    |
    // |   true     |  true    |    true    |
    // +------------+----------+------------+
    //
    return (config.pad_m || !needs_pad_m) && (config.pad_n || !needs_pad_n) &&
           (config.pad_k || !needs_pad_k) && (config.pad_o || !needs_pad_o);
}

std::vector<Operation> Operation::CreateOperations(const Problem& prob, const std::string& arch)
{
    std::vector<Operation> result;

    auto bucket = GetTileConfigsForHdim(arch, prob.dtype, prob.K, prob.O);
    auto pipelines =
        GetPipelineConfigs(arch, bucket.bucket_hdim, bucket.bucket_hdim_v, prob.has_bias);

    for(const auto& tile : bucket.tiles)
    {
        // Phase 12 correctness fix: skip tiles that violate the V-LDS
        // descriptor invariants on this arch. Without this filter, the
        // resulting Solution makes hipRTC static_assert during
        // compilation (see VLdsDescriptorValid comment for the full
        // explanation). This applies to BOTH the QR pipeline and the
        // async pipelines because the LDS path is shared.
        if(!VLdsDescriptorValid(tile, prob.dtype, arch))
            continue;

        // Compute exact padding needs for this tile
        bool needs_pad_m = (prob.M % tile.bm0 != 0);
        bool needs_pad_n = (prob.N % tile.bn0 != 0);
        bool needs_pad_k = (prob.K != bucket.bucket_hdim);
        bool needs_pad_o = (prob.O != bucket.bucket_hdim_v);

        // QR pipeline: create one operation with exact padding
        {
            Operation op;
            op.tile          = tile;
            op.pipeline      = "qr";
            op.is_causal     = prob.is_causal;
            op.is_v_rowmajor = prob.is_v_rowmajor;
            op.has_bias      = prob.has_bias;
            op.dtype         = prob.dtype;
            op.pad_m         = needs_pad_m;
            op.pad_n         = needs_pad_n;
            op.pad_k         = needs_pad_k;
            op.pad_o         = needs_pad_o;
            result.push_back(op);
        }

        // Async pipelines: use predefined configs with filters
        for(const auto& pipeline : pipelines)
        {
            if(prob.dtype == DataType::Half && (prob.K % 8 != 0 || prob.O % 8 != 0))
                continue;
            // Phase 12 correctness fix: filter tiles that make the K-LDS
            // async-load tensor descriptor degenerate (NumIssues = 0).
            if(!KLdsAsyncDescriptorValid(tile, prob.dtype, arch))
                continue;
            // Phase 12 correctness fix: for the qr_async_trload family,
            // the K-DRAM distribution's K1 must be a valid
            // amd_async_buffer_load vector size (4, 12, or 16 bytes).
            // The non-trload qr_async uses a different distribution that
            // always clamps to a valid vector, so this check only
            // applies to the trload variants.
            const bool is_trload =
                pipeline.name == "qr_async_trload" ||
                pipeline.name == "qr_async_trload_v3";
            if(is_trload && !TrloadKDramVectorValid(tile, prob.dtype, arch))
                continue;
            // Single-warp configs (rm0=1) produce incorrect results with async pipelines
            if(tile.rm0 == 1)
                continue;
            // (96, 128) bucket: rm0 >= 4 with pad_n=false produces incorrect results
            if(bucket.bucket_hdim == 96 && bucket.bucket_hdim_v == 128)
            {
                if(!pipeline.pad_n && tile.rm0 >= 4)
                    continue;
            }
            // (128, 128) bucket filters for async pipelines:
            //   - bn0=64, bk1=16 config produces invalid results
            //   - bk0=64 configs (MFMA 16x16x32) produce invalid results
            if(bucket.bucket_hdim == 128 && bucket.bucket_hdim_v == 128)
            {
                if(tile.bn0 == 64 && tile.bk1 == 16)
                    continue;
                if(tile.bk0 == 64)
                    continue;
            }
            // (192, 128) bucket filters for async pipelines
            if(bucket.bucket_hdim == 192 && bucket.bucket_hdim_v == 128)
            {
                // bk0=64 configs produce invalid results
                if(tile.bk0 == 64)
                    continue;
                // pad_n=false fails for wm0=32 (MFMA 32x32x16) or rm0>=4
                if(!pipeline.pad_n && (tile.wm0 == 32 || tile.rm0 >= 4))
                    continue;
            }
            // (192, 192) bucket filters for async pipelines
            if(bucket.bucket_hdim == 192 && bucket.bucket_hdim_v == 192)
            {
                // rm0=8 with wm0=32 always fails (even with pad_n=true)
                if(tile.rm0 == 8 && tile.wm0 == 32)
                    continue;
                // pad_n=false fails except for (rm0=2, wm0=32) and (rm0=8, wk0=16)
                if(!pipeline.pad_n)
                {
                    bool is_valid =
                        (tile.rm0 == 2 && tile.wm0 == 32) || (tile.rm0 == 8 && tile.wk0 == 16);
                    if(!is_valid)
                        continue;
                }
            }

            if(!IsPaddingCompatible(pipeline, prob, tile, bucket.bucket_hdim, bucket.bucket_hdim_v))
                continue;

            Operation op;
            op.tile          = tile;
            op.pipeline      = pipeline.name;
            op.is_causal     = prob.is_causal;
            op.is_v_rowmajor = prob.is_v_rowmajor;
            op.has_bias      = prob.has_bias;
            op.dtype         = prob.dtype;
            op.pad_m         = pipeline.pad_m;
            op.pad_n         = pipeline.pad_n;
            op.pad_k         = pipeline.pad_k;
            op.pad_o         = pipeline.pad_o;
            result.push_back(op);
        }
    }

    return result;
}

static std::string ToDataTypeString(DataType dtype)
{
    switch(dtype)
    {
    case DataType::Half: return "ck_tile::fp16_t";
    case DataType::Float: return "float";
    default: return "ck_tile::fp16_t";
    }
}

Solution Operation::ToSolution() const
{
    std::unordered_map<std::string, std::string> values = {
        {"DataType", ToDataTypeString(dtype)},

        {"BM0", std::to_string(tile.bm0)},
        {"BN0", std::to_string(tile.bn0)},
        {"BK0", std::to_string(tile.bk0)},
        {"BN1", std::to_string(tile.bn1)},
        {"BK1", std::to_string(tile.bk1)},
        {"BK0Max", std::to_string(tile.bk0max)},

        {"RM0", std::to_string(tile.rm0)},
        {"RN0", std::to_string(tile.rn0)},
        {"RK0", std::to_string(tile.rk0)},

        {"RM1", std::to_string(tile.rm1)},
        {"RN1", std::to_string(tile.rn1)},
        {"RK1", std::to_string(tile.rk1)},

        {"WM0", std::to_string(tile.wm0)},
        {"WN0", std::to_string(tile.wn0)},
        {"WK0", std::to_string(tile.wk0)},

        {"WM1", std::to_string(tile.wm1)},
        {"WN1", std::to_string(tile.wn1)},
        {"WK1", std::to_string(tile.wk1)},

        {"IsCausal", is_causal ? "true" : "false"},
        {"IsVRowMajor", is_v_rowmajor ? "true" : "false"},
        {"HasBias", has_bias ? "true" : "false"},

        {"PadM", pad_m ? "true" : "false"},
        {"PadN", pad_n ? "true" : "false"},
        {"PadK", pad_k ? "true" : "false"},
        {"PadO", pad_o ? "true" : "false"},

        {"PipelineTag",
         pipeline == "qr_async_trload" ? "QR_ASYNC_TRLOAD"
                                       : (pipeline == "qr_async" ? "QR_ASYNC" : "QR")},
    };

    return Solution{InterpolateString(FmhaFwdWrapperTemplate, values), std::move(values)};
}

} // namespace device_fmha_fwd
} // namespace host
} // namespace ck
