/*******************************************************************************
 *
 * MIT License
 *
 * Copyright (C) 2025 Advanced Micro Devices, Inc.
 *
 * IMPROVED VERSION WITH EMPIRICAL MICRO-BENCHMARK OPTIMIZATION
 *******************************************************************************/

#pragma once

#ifndef MULTI_MACROTILE_ORIGAMI_IMPROVED_HPP
#define MULTI_MACROTILE_ORIGAMI_IMPROVED_HPP
#endif

#include "multi_macrotile_origami.hpp"

namespace OrigamiConstants {
    constexpr double MACROTILE_MISMATCH_THRESHOLD = 0.75;
    constexpr int    MICRO_BENCH_ITERS = 3;
}

// Structure to hold one candidate split configuration for empirical testing
struct OrigamiCandidate
{
    std::vector<int64_t> split_sizes;
    std::string label;
};

/**
 * @brief Check if a split should be enabled based on MacroTile preservation
 */
inline bool shouldEnableMultiMacroTileSplit(
    hipblasLtHandle_t handle,
    int64_t M, int64_t N, int64_t K,
    int num_splits,
    bool is_m_split,
    hipblasOperation_t transA,
    hipblasOperation_t transB,
    hipDataType a_type,
    hipDataType b_type,
    hipDataType c_type,
    hipDataType d_type,
    hipblasComputeType_t compute_type)
{
    using namespace OrigamiConstants;

    auto baseline_sols = queryAllSolutionsForSubProblem(handle, M, N, K, transA, transB,
                                                         a_type, b_type, c_type, d_type, compute_type);
    if (baseline_sols.empty())
        return false;

    size_t baseline_mt_m, baseline_mt_n, baseline_mt_k;
    if (!parseMacroTileFromSolutionName(baseline_sols[0].solution_name, baseline_mt_m, baseline_mt_n, baseline_mt_k))
        return false;

    int64_t M_split = is_m_split ? (M / num_splits) : M;
    int64_t N_split = is_m_split ? N : (N / num_splits);

    auto split_sols = queryAllSolutionsForSubProblem(handle, M_split, N_split, K, transA, transB,
                                                      a_type, b_type, c_type, d_type, compute_type);
    if (split_sols.empty())
        return false;

    size_t split_mt_m, split_mt_n, split_mt_k;
    if (!parseMacroTileFromSolutionName(split_sols[0].solution_name, split_mt_m, split_mt_n, split_mt_k))
        return false;

    bool mt_m_ok = split_mt_m >= baseline_mt_m * MACROTILE_MISMATCH_THRESHOLD;
    bool mt_n_ok = split_mt_n >= baseline_mt_n * MACROTILE_MISMATCH_THRESHOLD;

    return mt_m_ok && mt_n_ok;
}

/**
 * @brief Generate multiple candidate split configurations for empirical testing.
 *
 * Returns a vector of candidates including:
 *   - Uniform 50/50
 *   - Asymmetric 60/40 and 40/60
 *   - Asymmetric 70/30 and 30/70
 *   - Power-of-2 biased
 *
 * All splits are aligned to the MacroTile boundary.
 */
inline std::vector<OrigamiCandidate> generateOrigamiCandidates(
    int64_t total_size,
    int macrotile_size)
{
    std::vector<OrigamiCandidate> candidates;
    int mt = std::max(macrotile_size, 1);

    auto make_split = [&](double ratio, const std::string& label) {
        int64_t s1 = (int64_t)(total_size * ratio);
        s1 = (s1 / mt) * mt;
        s1 = std::max(s1, (int64_t)mt);
        s1 = std::min(s1, total_size - (int64_t)mt);
        int64_t s2 = total_size - s1;
        if (s2 >= mt)
            candidates.push_back({{s1, s2}, label});
    };

    make_split(0.50, "uniform-50/50");
    make_split(0.60, "asym-60/40");
    make_split(0.40, "asym-40/60");
    make_split(0.70, "asym-70/30");
    make_split(0.30, "asym-30/70");

    // Power-of-2 biased: find largest pow2 <= total/2, remainder gets the rest
    {
        int64_t target = total_size / 2;
        int64_t pow2 = 1;
        while (pow2 * 2 <= target) pow2 *= 2;
        // Use next pow2 if closer
        int64_t s1 = (target - pow2 > pow2 / 4) ? pow2 * 2 : pow2;
        s1 = std::min(s1, total_size - (int64_t)mt);
        int64_t s2 = total_size - s1;
        if (s1 >= mt && s2 >= mt)
            candidates.push_back({{s1, s2}, "pow2-biased"});
    }

    // Deduplicate: remove candidates with identical split sizes
    std::vector<OrigamiCandidate> unique;
    for (auto& c : candidates) {
        bool dup = false;
        for (auto& u : unique) {
            if (u.split_sizes[0] == c.split_sizes[0])
                { dup = true; break; }
        }
        if (!dup) unique.push_back(c);
    }

    return unique;
}

/**
 * @brief Origami with empirical micro-benchmark.
 *
 * Instead of estimation, returns multiple candidate splits.
 * The calling code (testing_matmul.hpp) will micro-benchmark each
 * candidate and pick the winner.
 *
 * Returns the uniform split as default. The candidates are stored
 * in a global for the timing path to access.
 */

// Thread-local storage for candidate splits generated by Origami
// The timing path reads this to run the empirical micro-benchmark.
inline std::vector<OrigamiCandidate>& getOrigamiCandidates()
{
    static thread_local std::vector<OrigamiCandidate> candidates;
    return candidates;
}

inline std::vector<int64_t> computeOrigamiOptimizedSplitsWithHandle(
    hipblasLtHandle_t handle,
    int64_t total_size,
    int num_splits,
    int macrotile_size,
    int64_t other_dim,
    int64_t K,
    bool is_m_split,
    hipblasOperation_t transA,
    hipblasOperation_t transB,
    hipDataType a_type,
    hipDataType b_type,
    hipDataType c_type,
    hipDataType d_type,
    hipblasComputeType_t compute_type)
{
    int64_t M = is_m_split ? total_size : other_dim;
    int64_t N = is_m_split ? other_dim : total_size;

    // P2: MacroTile preservation check
    if (!shouldEnableMultiMacroTileSplit(handle, M, N, K, num_splits, is_m_split,
                                         transA, transB, a_type, b_type, c_type, d_type, compute_type))
        return {};

    // Generate candidate split configurations for empirical testing
    auto candidates = generateOrigamiCandidates(total_size, macrotile_size);

    // Store candidates for the timing path to micro-benchmark
    getOrigamiCandidates() = candidates;

    // Return the first candidate (uniform) as the default split.
    // The timing path will override this if a better candidate is found.
    if (!candidates.empty())
        return candidates[0].split_sizes;

    return {};
}
