# Copyright Advanced Micro Devices, Inc., or its affiliates.
# SPDX-License-Identifier: MIT

# See here for image contents: https://github.com/devcontainers/images/tree/main/src/base-ubuntu

##
## Common with other Dockerfiles.
##

# ubuntu-20.04 = focal
# ubuntu-22.04 = jammy
ARG BASE_IMAGE=jammy
FROM mcr.microsoft.com/devcontainers/base:${BASE_IMAGE}

RUN ( \
    echo "base_image: ${BASE_IMAGE}" && \
    echo "rocroller: gcc-13" \
    ) > /.container_info.txt

ARG DEBIAN_FRONTEND=noninteractive

# Propagate the environment variable HTTP_PROXY into the apt config if it's set.
RUN [ -z ${HTTP_PROXY} ] || (echo "Acquire::http::Proxy \"${HTTP_PROXY}\";" > /etc/apt/apt.conf.d/proxy)

# Add PPA with g++-13
RUN apt-get update && apt-get reinstall -y software-properties-common && add-apt-repository -y ppa:ubuntu-toolchain-r/test

RUN apt-get update && apt-get install -y \
   bc \
   gdb \
   libopenblas-dev \
   libncurses-dev \
   m4 \
   make \
   nano \
   netcat-traditional \
   ninja-build \
   python3-dev \
   python3-venv \
   vim \
   wget \
   xz-utils \
   libdw-dev

# CMake
ARG CMAKE_VERSION=3.25.2
WORKDIR /tmp
RUN wget -nv -O cmake-install.sh https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-linux-x86_64.sh \
    && sh cmake-install.sh --prefix=/usr/local --skip-license \
    && rm -rf /tmp/*

# clang-format from ROCm 4.3.1
WORKDIR /tmp
RUN wget -nv -O libtinfo5.deb http://security.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2ubuntu0.1_amd64.deb \
    && apt-get install -y --no-install-recommends ./libtinfo5.deb \
    && wget -nv -O llvm-amdgpu.deb https://repo.radeon.com/rocm/apt/4.3.1/pool/main/l/llvm-amdgpu4.3.1/llvm-amdgpu4.3.1_13.0.0.21313.40301_amd64.deb \
    && ar x llvm-amdgpu.deb data.tar.xz \
    && tar xJf data.tar.xz --strip-components=5 ./opt/rocm-4.3.1/llvm/bin/clang-format \
    && mkdir -p /opt/clang-format/bin \
    && mv clang-format /opt/clang-format/bin \
    && rm -rf /tmp/* /var/lib/apt/lists/*
ENV PATH="/opt/clang-format/bin:${PATH}"

# ccache (needs cmake ninja)
WORKDIR /tmp
RUN wget -nv -O ccache-4.11.tar.gz https://github.com/ccache/ccache/releases/download/v4.11/ccache-4.11.tar.gz \
    && tar xf ccache-4.11.tar.gz \
    && cmake \
        -S ccache-4.11 \
        -B ccache-4.11_build \
        -G Ninja \
        -DCMAKE_BUILD_TYPE=Release \
        -DENABLE_TESTING=OFF \
        -DREDIS_STORAGE_BACKEND=OFF \
    && cmake --build ccache-4.11_build --target install \
    && rm -rf /tmp/*

# cppcheck
WORKDIR /tmp
RUN wget -nv -O cppcheck_2.9.3.zip https://github.com/danmar/cppcheck/archive/refs/tags/2.9.3.zip \
    && unzip cppcheck_2.9.3.zip \
    && cmake \
        -S cppcheck-2.9.3 \
        -B cppcheck-2.9.3_build \
        -G Ninja \
        -DCMAKE_BUILD_TYPE=Release \
    && cmake --build cppcheck-2.9.3_build --target install \
    && rm -rf /tmp/*

# graph & documentation & perf
RUN apt-get update && apt-get install -y \
      graphviz \
      doxygen \
      linux-tools-common linux-tools-generic

# Python
RUN python3 -m venv /opt/rr-python-venv
ENV PATH="/opt/rr-python-venv/bin:$PATH"
COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt && rm /tmp/requirements.txt

# HipBLASLt
RUN apt-get update && apt-get install -y \
    libmsgpack-dev \
    libboost-program-options-dev \
    libboost-filesystem-dev \
    kmod

##
## Specific to this Dockerfile.  Put faster-changing-things last.
##

# ROCM
# Set URL to something like https://repo.radeon.com/amdgpu-install/7.2.1/ubuntu/jammy/amdgpu-install_7.2.1.70201-1_all.deb
ARG ROCROLLER_AMDGPU_URL
ARG ROCROLLER_AMDGPU_BUILD_NUMBER=
ARG ROCROLLER_AMDGPU_BUILD_URI=
WORKDIR /tmp
RUN wget -nv -O amdgpu_install.deb ${ROCROLLER_AMDGPU_URL} \
    && apt-get update \
    && apt-get install -y --no-install-recommends ./amdgpu_install.deb \
    && if test -n "${ROCROLLER_AMDGPU_BUILD_NUMBER}"; then amdgpu-repo --amdgpu-build=${ROCROLLER_AMDGPU_BUILD_NUMBER} --rocm-build=${ROCROLLER_AMDGPU_BUILD_URI}; fi \
    && amdgpu-install -y --usecase=rocmdev --no-dkms \
    && apt-get update && apt-get install -y --no-install-recommends \
        rocm-llvm-dev \
        hipblas-common-dev \
    && rm -rf /tmp/* /var/lib/apt/lists/*

# g++-13
RUN apt-get update && apt-get install -y \
      g++-13

ENV CXX=/usr/bin/g++-13
ENV CC=/usr/bin/gcc-13

ADD docker/install-rocprof-trace-decoder /tmp
RUN /tmp/install-rocprof-trace-decoder && rm /tmp/install-rocprof-trace-decoder

# Clean image
RUN apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/*
