// Copyright (c) 2025, Advanced Micro Devices, Inc. All rights reserved.
//
// See LICENSE for license information.
//
// Pinned AGPR/VGPR register primitives for hand-tuned kernels.

#pragma once

#include <cstdint>

#include "primus_turbo/dtype.h"

namespace primus_turbo::device {

// ════════════════════════════════════════════════════════════════
//  AGPR (Accumulator General Purpose Register)
// ════════════════════════════════════════════════════════════════

// ── Single-register operations ──

template <int AGPR> __device__ __forceinline__ void clobber_agpr_one() {
    static_assert(AGPR >= 0 && AGPR <= 255, "AGPR must be in [0, 255]");
    // clang-format off
#define CLOBBER_AREG_CASE(N) case N: asm volatile("" ::: "a" #N); break;
    switch (AGPR) {
        CLOBBER_AREG_CASE(0)   CLOBBER_AREG_CASE(1)   CLOBBER_AREG_CASE(2)   CLOBBER_AREG_CASE(3)   CLOBBER_AREG_CASE(4)   CLOBBER_AREG_CASE(5)   CLOBBER_AREG_CASE(6)   CLOBBER_AREG_CASE(7)
        CLOBBER_AREG_CASE(8)   CLOBBER_AREG_CASE(9)   CLOBBER_AREG_CASE(10)  CLOBBER_AREG_CASE(11)  CLOBBER_AREG_CASE(12)  CLOBBER_AREG_CASE(13)  CLOBBER_AREG_CASE(14)  CLOBBER_AREG_CASE(15)
        CLOBBER_AREG_CASE(16)  CLOBBER_AREG_CASE(17)  CLOBBER_AREG_CASE(18)  CLOBBER_AREG_CASE(19)  CLOBBER_AREG_CASE(20)  CLOBBER_AREG_CASE(21)  CLOBBER_AREG_CASE(22)  CLOBBER_AREG_CASE(23)
        CLOBBER_AREG_CASE(24)  CLOBBER_AREG_CASE(25)  CLOBBER_AREG_CASE(26)  CLOBBER_AREG_CASE(27)  CLOBBER_AREG_CASE(28)  CLOBBER_AREG_CASE(29)  CLOBBER_AREG_CASE(30)  CLOBBER_AREG_CASE(31)
        CLOBBER_AREG_CASE(32)  CLOBBER_AREG_CASE(33)  CLOBBER_AREG_CASE(34)  CLOBBER_AREG_CASE(35)  CLOBBER_AREG_CASE(36)  CLOBBER_AREG_CASE(37)  CLOBBER_AREG_CASE(38)  CLOBBER_AREG_CASE(39)
        CLOBBER_AREG_CASE(40)  CLOBBER_AREG_CASE(41)  CLOBBER_AREG_CASE(42)  CLOBBER_AREG_CASE(43)  CLOBBER_AREG_CASE(44)  CLOBBER_AREG_CASE(45)  CLOBBER_AREG_CASE(46)  CLOBBER_AREG_CASE(47)
        CLOBBER_AREG_CASE(48)  CLOBBER_AREG_CASE(49)  CLOBBER_AREG_CASE(50)  CLOBBER_AREG_CASE(51)  CLOBBER_AREG_CASE(52)  CLOBBER_AREG_CASE(53)  CLOBBER_AREG_CASE(54)  CLOBBER_AREG_CASE(55)
        CLOBBER_AREG_CASE(56)  CLOBBER_AREG_CASE(57)  CLOBBER_AREG_CASE(58)  CLOBBER_AREG_CASE(59)  CLOBBER_AREG_CASE(60)  CLOBBER_AREG_CASE(61)  CLOBBER_AREG_CASE(62)  CLOBBER_AREG_CASE(63)
        CLOBBER_AREG_CASE(64)  CLOBBER_AREG_CASE(65)  CLOBBER_AREG_CASE(66)  CLOBBER_AREG_CASE(67)  CLOBBER_AREG_CASE(68)  CLOBBER_AREG_CASE(69)  CLOBBER_AREG_CASE(70)  CLOBBER_AREG_CASE(71)
        CLOBBER_AREG_CASE(72)  CLOBBER_AREG_CASE(73)  CLOBBER_AREG_CASE(74)  CLOBBER_AREG_CASE(75)  CLOBBER_AREG_CASE(76)  CLOBBER_AREG_CASE(77)  CLOBBER_AREG_CASE(78)  CLOBBER_AREG_CASE(79)
        CLOBBER_AREG_CASE(80)  CLOBBER_AREG_CASE(81)  CLOBBER_AREG_CASE(82)  CLOBBER_AREG_CASE(83)  CLOBBER_AREG_CASE(84)  CLOBBER_AREG_CASE(85)  CLOBBER_AREG_CASE(86)  CLOBBER_AREG_CASE(87)
        CLOBBER_AREG_CASE(88)  CLOBBER_AREG_CASE(89)  CLOBBER_AREG_CASE(90)  CLOBBER_AREG_CASE(91)  CLOBBER_AREG_CASE(92)  CLOBBER_AREG_CASE(93)  CLOBBER_AREG_CASE(94)  CLOBBER_AREG_CASE(95)
        CLOBBER_AREG_CASE(96)  CLOBBER_AREG_CASE(97)  CLOBBER_AREG_CASE(98)  CLOBBER_AREG_CASE(99)  CLOBBER_AREG_CASE(100) CLOBBER_AREG_CASE(101) CLOBBER_AREG_CASE(102) CLOBBER_AREG_CASE(103)
        CLOBBER_AREG_CASE(104) CLOBBER_AREG_CASE(105) CLOBBER_AREG_CASE(106) CLOBBER_AREG_CASE(107) CLOBBER_AREG_CASE(108) CLOBBER_AREG_CASE(109) CLOBBER_AREG_CASE(110) CLOBBER_AREG_CASE(111)
        CLOBBER_AREG_CASE(112) CLOBBER_AREG_CASE(113) CLOBBER_AREG_CASE(114) CLOBBER_AREG_CASE(115) CLOBBER_AREG_CASE(116) CLOBBER_AREG_CASE(117) CLOBBER_AREG_CASE(118) CLOBBER_AREG_CASE(119)
        CLOBBER_AREG_CASE(120) CLOBBER_AREG_CASE(121) CLOBBER_AREG_CASE(122) CLOBBER_AREG_CASE(123) CLOBBER_AREG_CASE(124) CLOBBER_AREG_CASE(125) CLOBBER_AREG_CASE(126) CLOBBER_AREG_CASE(127)
        CLOBBER_AREG_CASE(128) CLOBBER_AREG_CASE(129) CLOBBER_AREG_CASE(130) CLOBBER_AREG_CASE(131) CLOBBER_AREG_CASE(132) CLOBBER_AREG_CASE(133) CLOBBER_AREG_CASE(134) CLOBBER_AREG_CASE(135)
        CLOBBER_AREG_CASE(136) CLOBBER_AREG_CASE(137) CLOBBER_AREG_CASE(138) CLOBBER_AREG_CASE(139) CLOBBER_AREG_CASE(140) CLOBBER_AREG_CASE(141) CLOBBER_AREG_CASE(142) CLOBBER_AREG_CASE(143)
        CLOBBER_AREG_CASE(144) CLOBBER_AREG_CASE(145) CLOBBER_AREG_CASE(146) CLOBBER_AREG_CASE(147) CLOBBER_AREG_CASE(148) CLOBBER_AREG_CASE(149) CLOBBER_AREG_CASE(150) CLOBBER_AREG_CASE(151)
        CLOBBER_AREG_CASE(152) CLOBBER_AREG_CASE(153) CLOBBER_AREG_CASE(154) CLOBBER_AREG_CASE(155) CLOBBER_AREG_CASE(156) CLOBBER_AREG_CASE(157) CLOBBER_AREG_CASE(158) CLOBBER_AREG_CASE(159)
        CLOBBER_AREG_CASE(160) CLOBBER_AREG_CASE(161) CLOBBER_AREG_CASE(162) CLOBBER_AREG_CASE(163) CLOBBER_AREG_CASE(164) CLOBBER_AREG_CASE(165) CLOBBER_AREG_CASE(166) CLOBBER_AREG_CASE(167)
        CLOBBER_AREG_CASE(168) CLOBBER_AREG_CASE(169) CLOBBER_AREG_CASE(170) CLOBBER_AREG_CASE(171) CLOBBER_AREG_CASE(172) CLOBBER_AREG_CASE(173) CLOBBER_AREG_CASE(174) CLOBBER_AREG_CASE(175)
        CLOBBER_AREG_CASE(176) CLOBBER_AREG_CASE(177) CLOBBER_AREG_CASE(178) CLOBBER_AREG_CASE(179) CLOBBER_AREG_CASE(180) CLOBBER_AREG_CASE(181) CLOBBER_AREG_CASE(182) CLOBBER_AREG_CASE(183)
        CLOBBER_AREG_CASE(184) CLOBBER_AREG_CASE(185) CLOBBER_AREG_CASE(186) CLOBBER_AREG_CASE(187) CLOBBER_AREG_CASE(188) CLOBBER_AREG_CASE(189) CLOBBER_AREG_CASE(190) CLOBBER_AREG_CASE(191)
        CLOBBER_AREG_CASE(192) CLOBBER_AREG_CASE(193) CLOBBER_AREG_CASE(194) CLOBBER_AREG_CASE(195) CLOBBER_AREG_CASE(196) CLOBBER_AREG_CASE(197) CLOBBER_AREG_CASE(198) CLOBBER_AREG_CASE(199)
        CLOBBER_AREG_CASE(200) CLOBBER_AREG_CASE(201) CLOBBER_AREG_CASE(202) CLOBBER_AREG_CASE(203) CLOBBER_AREG_CASE(204) CLOBBER_AREG_CASE(205) CLOBBER_AREG_CASE(206) CLOBBER_AREG_CASE(207)
        CLOBBER_AREG_CASE(208) CLOBBER_AREG_CASE(209) CLOBBER_AREG_CASE(210) CLOBBER_AREG_CASE(211) CLOBBER_AREG_CASE(212) CLOBBER_AREG_CASE(213) CLOBBER_AREG_CASE(214) CLOBBER_AREG_CASE(215)
        CLOBBER_AREG_CASE(216) CLOBBER_AREG_CASE(217) CLOBBER_AREG_CASE(218) CLOBBER_AREG_CASE(219) CLOBBER_AREG_CASE(220) CLOBBER_AREG_CASE(221) CLOBBER_AREG_CASE(222) CLOBBER_AREG_CASE(223)
        CLOBBER_AREG_CASE(224) CLOBBER_AREG_CASE(225) CLOBBER_AREG_CASE(226) CLOBBER_AREG_CASE(227) CLOBBER_AREG_CASE(228) CLOBBER_AREG_CASE(229) CLOBBER_AREG_CASE(230) CLOBBER_AREG_CASE(231)
        CLOBBER_AREG_CASE(232) CLOBBER_AREG_CASE(233) CLOBBER_AREG_CASE(234) CLOBBER_AREG_CASE(235) CLOBBER_AREG_CASE(236) CLOBBER_AREG_CASE(237) CLOBBER_AREG_CASE(238) CLOBBER_AREG_CASE(239)
        CLOBBER_AREG_CASE(240) CLOBBER_AREG_CASE(241) CLOBBER_AREG_CASE(242) CLOBBER_AREG_CASE(243) CLOBBER_AREG_CASE(244) CLOBBER_AREG_CASE(245) CLOBBER_AREG_CASE(246) CLOBBER_AREG_CASE(247)
        CLOBBER_AREG_CASE(248) CLOBBER_AREG_CASE(249) CLOBBER_AREG_CASE(250) CLOBBER_AREG_CASE(251) CLOBBER_AREG_CASE(252) CLOBBER_AREG_CASE(253) CLOBBER_AREG_CASE(254) CLOBBER_AREG_CASE(255)
    }
#undef CLOBBER_AREG_CASE
    // clang-format on
}

template <int AC> __device__ __forceinline__ void zero_agpr() {
    asm volatile("v_accvgpr_write_b32 a[%0], 0" : : "n"(AC));
}

// Read N consecutive AGPRs starting at AC, returned as type T.
// T must be 32-bit aligned (sizeof(T) must be a multiple of 4).
template <typename T, int AC> __device__ __forceinline__ T read_agpr() {
    static constexpr int N = sizeof(T) / sizeof(uint32_t);
    static_assert(sizeof(T) % sizeof(uint32_t) == 0, "T must be 32-bit aligned");
    static_assert(N >= 1 && N <= 16, "read_agpr supports 1-16 registers");
    uint32_t raw[N];
    // clang-format off
    if constexpr (N >=  1) asm volatile("v_accvgpr_read_b32 %0, a[%1]" : "=v"(raw[0])  : "n"(AC));
    if constexpr (N >=  2) asm volatile("v_accvgpr_read_b32 %0, a[%1]" : "=v"(raw[1])  : "n"(AC + 1));
    if constexpr (N >=  3) asm volatile("v_accvgpr_read_b32 %0, a[%1]" : "=v"(raw[2])  : "n"(AC + 2));
    if constexpr (N >=  4) asm volatile("v_accvgpr_read_b32 %0, a[%1]" : "=v"(raw[3])  : "n"(AC + 3));
    if constexpr (N >=  5) asm volatile("v_accvgpr_read_b32 %0, a[%1]" : "=v"(raw[4])  : "n"(AC + 4));
    if constexpr (N >=  6) asm volatile("v_accvgpr_read_b32 %0, a[%1]" : "=v"(raw[5])  : "n"(AC + 5));
    if constexpr (N >=  7) asm volatile("v_accvgpr_read_b32 %0, a[%1]" : "=v"(raw[6])  : "n"(AC + 6));
    if constexpr (N >=  8) asm volatile("v_accvgpr_read_b32 %0, a[%1]" : "=v"(raw[7])  : "n"(AC + 7));
    if constexpr (N >=  9) asm volatile("v_accvgpr_read_b32 %0, a[%1]" : "=v"(raw[8])  : "n"(AC + 8));
    if constexpr (N >= 10) asm volatile("v_accvgpr_read_b32 %0, a[%1]" : "=v"(raw[9])  : "n"(AC + 9));
    if constexpr (N >= 11) asm volatile("v_accvgpr_read_b32 %0, a[%1]" : "=v"(raw[10]) : "n"(AC + 10));
    if constexpr (N >= 12) asm volatile("v_accvgpr_read_b32 %0, a[%1]" : "=v"(raw[11]) : "n"(AC + 11));
    if constexpr (N >= 13) asm volatile("v_accvgpr_read_b32 %0, a[%1]" : "=v"(raw[12]) : "n"(AC + 12));
    if constexpr (N >= 14) asm volatile("v_accvgpr_read_b32 %0, a[%1]" : "=v"(raw[13]) : "n"(AC + 13));
    if constexpr (N >= 15) asm volatile("v_accvgpr_read_b32 %0, a[%1]" : "=v"(raw[14]) : "n"(AC + 14));
    if constexpr (N >= 16) asm volatile("v_accvgpr_read_b32 %0, a[%1]" : "=v"(raw[15]) : "n"(AC + 15));
    // clang-format on
    return __builtin_bit_cast(T, raw);
}

// ── Range operations ──

template <int START, int END> __device__ __forceinline__ void reserve_agpr_range() {
    if constexpr (START <= END) {
        clobber_agpr_one<START>();
        if constexpr (START < END)
            reserve_agpr_range<START + 1, END>();
    }
}

template <int START, int END> __device__ __forceinline__ void zero_agpr_range() {
    if constexpr (START <= END) {
        zero_agpr<START>();
        if constexpr (START < END)
            zero_agpr_range<START + 1, END>();
    }
}

// ════════════════════════════════════════════════════════════════
//  VGPR (Vector General Purpose Register)
// ════════════════════════════════════════════════════════════════

// ── Single-register operations ──

template <int VGPR> __device__ __forceinline__ void clobber_vgpr_one() {
    static_assert(VGPR >= 0 && VGPR <= 255, "VGPR must be in [0, 255]");
    // clang-format off
#define CLOBBER_VREG_CASE(N) case N: asm volatile("" ::: "v" #N); break;
    switch (VGPR) {
        CLOBBER_VREG_CASE(0)   CLOBBER_VREG_CASE(1)   CLOBBER_VREG_CASE(2)   CLOBBER_VREG_CASE(3)   CLOBBER_VREG_CASE(4)   CLOBBER_VREG_CASE(5)   CLOBBER_VREG_CASE(6)   CLOBBER_VREG_CASE(7)
        CLOBBER_VREG_CASE(8)   CLOBBER_VREG_CASE(9)   CLOBBER_VREG_CASE(10)  CLOBBER_VREG_CASE(11)  CLOBBER_VREG_CASE(12)  CLOBBER_VREG_CASE(13)  CLOBBER_VREG_CASE(14)  CLOBBER_VREG_CASE(15)
        CLOBBER_VREG_CASE(16)  CLOBBER_VREG_CASE(17)  CLOBBER_VREG_CASE(18)  CLOBBER_VREG_CASE(19)  CLOBBER_VREG_CASE(20)  CLOBBER_VREG_CASE(21)  CLOBBER_VREG_CASE(22)  CLOBBER_VREG_CASE(23)
        CLOBBER_VREG_CASE(24)  CLOBBER_VREG_CASE(25)  CLOBBER_VREG_CASE(26)  CLOBBER_VREG_CASE(27)  CLOBBER_VREG_CASE(28)  CLOBBER_VREG_CASE(29)  CLOBBER_VREG_CASE(30)  CLOBBER_VREG_CASE(31)
        CLOBBER_VREG_CASE(32)  CLOBBER_VREG_CASE(33)  CLOBBER_VREG_CASE(34)  CLOBBER_VREG_CASE(35)  CLOBBER_VREG_CASE(36)  CLOBBER_VREG_CASE(37)  CLOBBER_VREG_CASE(38)  CLOBBER_VREG_CASE(39)
        CLOBBER_VREG_CASE(40)  CLOBBER_VREG_CASE(41)  CLOBBER_VREG_CASE(42)  CLOBBER_VREG_CASE(43)  CLOBBER_VREG_CASE(44)  CLOBBER_VREG_CASE(45)  CLOBBER_VREG_CASE(46)  CLOBBER_VREG_CASE(47)
        CLOBBER_VREG_CASE(48)  CLOBBER_VREG_CASE(49)  CLOBBER_VREG_CASE(50)  CLOBBER_VREG_CASE(51)  CLOBBER_VREG_CASE(52)  CLOBBER_VREG_CASE(53)  CLOBBER_VREG_CASE(54)  CLOBBER_VREG_CASE(55)
        CLOBBER_VREG_CASE(56)  CLOBBER_VREG_CASE(57)  CLOBBER_VREG_CASE(58)  CLOBBER_VREG_CASE(59)  CLOBBER_VREG_CASE(60)  CLOBBER_VREG_CASE(61)  CLOBBER_VREG_CASE(62)  CLOBBER_VREG_CASE(63)
        CLOBBER_VREG_CASE(64)  CLOBBER_VREG_CASE(65)  CLOBBER_VREG_CASE(66)  CLOBBER_VREG_CASE(67)  CLOBBER_VREG_CASE(68)  CLOBBER_VREG_CASE(69)  CLOBBER_VREG_CASE(70)  CLOBBER_VREG_CASE(71)
        CLOBBER_VREG_CASE(72)  CLOBBER_VREG_CASE(73)  CLOBBER_VREG_CASE(74)  CLOBBER_VREG_CASE(75)  CLOBBER_VREG_CASE(76)  CLOBBER_VREG_CASE(77)  CLOBBER_VREG_CASE(78)  CLOBBER_VREG_CASE(79)
        CLOBBER_VREG_CASE(80)  CLOBBER_VREG_CASE(81)  CLOBBER_VREG_CASE(82)  CLOBBER_VREG_CASE(83)  CLOBBER_VREG_CASE(84)  CLOBBER_VREG_CASE(85)  CLOBBER_VREG_CASE(86)  CLOBBER_VREG_CASE(87)
        CLOBBER_VREG_CASE(88)  CLOBBER_VREG_CASE(89)  CLOBBER_VREG_CASE(90)  CLOBBER_VREG_CASE(91)  CLOBBER_VREG_CASE(92)  CLOBBER_VREG_CASE(93)  CLOBBER_VREG_CASE(94)  CLOBBER_VREG_CASE(95)
        CLOBBER_VREG_CASE(96)  CLOBBER_VREG_CASE(97)  CLOBBER_VREG_CASE(98)  CLOBBER_VREG_CASE(99)  CLOBBER_VREG_CASE(100) CLOBBER_VREG_CASE(101) CLOBBER_VREG_CASE(102) CLOBBER_VREG_CASE(103)
        CLOBBER_VREG_CASE(104) CLOBBER_VREG_CASE(105) CLOBBER_VREG_CASE(106) CLOBBER_VREG_CASE(107) CLOBBER_VREG_CASE(108) CLOBBER_VREG_CASE(109) CLOBBER_VREG_CASE(110) CLOBBER_VREG_CASE(111)
        CLOBBER_VREG_CASE(112) CLOBBER_VREG_CASE(113) CLOBBER_VREG_CASE(114) CLOBBER_VREG_CASE(115) CLOBBER_VREG_CASE(116) CLOBBER_VREG_CASE(117) CLOBBER_VREG_CASE(118) CLOBBER_VREG_CASE(119)
        CLOBBER_VREG_CASE(120) CLOBBER_VREG_CASE(121) CLOBBER_VREG_CASE(122) CLOBBER_VREG_CASE(123) CLOBBER_VREG_CASE(124) CLOBBER_VREG_CASE(125) CLOBBER_VREG_CASE(126) CLOBBER_VREG_CASE(127)
        CLOBBER_VREG_CASE(128) CLOBBER_VREG_CASE(129) CLOBBER_VREG_CASE(130) CLOBBER_VREG_CASE(131) CLOBBER_VREG_CASE(132) CLOBBER_VREG_CASE(133) CLOBBER_VREG_CASE(134) CLOBBER_VREG_CASE(135)
        CLOBBER_VREG_CASE(136) CLOBBER_VREG_CASE(137) CLOBBER_VREG_CASE(138) CLOBBER_VREG_CASE(139) CLOBBER_VREG_CASE(140) CLOBBER_VREG_CASE(141) CLOBBER_VREG_CASE(142) CLOBBER_VREG_CASE(143)
        CLOBBER_VREG_CASE(144) CLOBBER_VREG_CASE(145) CLOBBER_VREG_CASE(146) CLOBBER_VREG_CASE(147) CLOBBER_VREG_CASE(148) CLOBBER_VREG_CASE(149) CLOBBER_VREG_CASE(150) CLOBBER_VREG_CASE(151)
        CLOBBER_VREG_CASE(152) CLOBBER_VREG_CASE(153) CLOBBER_VREG_CASE(154) CLOBBER_VREG_CASE(155) CLOBBER_VREG_CASE(156) CLOBBER_VREG_CASE(157) CLOBBER_VREG_CASE(158) CLOBBER_VREG_CASE(159)
        CLOBBER_VREG_CASE(160) CLOBBER_VREG_CASE(161) CLOBBER_VREG_CASE(162) CLOBBER_VREG_CASE(163) CLOBBER_VREG_CASE(164) CLOBBER_VREG_CASE(165) CLOBBER_VREG_CASE(166) CLOBBER_VREG_CASE(167)
        CLOBBER_VREG_CASE(168) CLOBBER_VREG_CASE(169) CLOBBER_VREG_CASE(170) CLOBBER_VREG_CASE(171) CLOBBER_VREG_CASE(172) CLOBBER_VREG_CASE(173) CLOBBER_VREG_CASE(174) CLOBBER_VREG_CASE(175)
        CLOBBER_VREG_CASE(176) CLOBBER_VREG_CASE(177) CLOBBER_VREG_CASE(178) CLOBBER_VREG_CASE(179) CLOBBER_VREG_CASE(180) CLOBBER_VREG_CASE(181) CLOBBER_VREG_CASE(182) CLOBBER_VREG_CASE(183)
        CLOBBER_VREG_CASE(184) CLOBBER_VREG_CASE(185) CLOBBER_VREG_CASE(186) CLOBBER_VREG_CASE(187) CLOBBER_VREG_CASE(188) CLOBBER_VREG_CASE(189) CLOBBER_VREG_CASE(190) CLOBBER_VREG_CASE(191)
        CLOBBER_VREG_CASE(192) CLOBBER_VREG_CASE(193) CLOBBER_VREG_CASE(194) CLOBBER_VREG_CASE(195) CLOBBER_VREG_CASE(196) CLOBBER_VREG_CASE(197) CLOBBER_VREG_CASE(198) CLOBBER_VREG_CASE(199)
        CLOBBER_VREG_CASE(200) CLOBBER_VREG_CASE(201) CLOBBER_VREG_CASE(202) CLOBBER_VREG_CASE(203) CLOBBER_VREG_CASE(204) CLOBBER_VREG_CASE(205) CLOBBER_VREG_CASE(206) CLOBBER_VREG_CASE(207)
        CLOBBER_VREG_CASE(208) CLOBBER_VREG_CASE(209) CLOBBER_VREG_CASE(210) CLOBBER_VREG_CASE(211) CLOBBER_VREG_CASE(212) CLOBBER_VREG_CASE(213) CLOBBER_VREG_CASE(214) CLOBBER_VREG_CASE(215)
        CLOBBER_VREG_CASE(216) CLOBBER_VREG_CASE(217) CLOBBER_VREG_CASE(218) CLOBBER_VREG_CASE(219) CLOBBER_VREG_CASE(220) CLOBBER_VREG_CASE(221) CLOBBER_VREG_CASE(222) CLOBBER_VREG_CASE(223)
        CLOBBER_VREG_CASE(224) CLOBBER_VREG_CASE(225) CLOBBER_VREG_CASE(226) CLOBBER_VREG_CASE(227) CLOBBER_VREG_CASE(228) CLOBBER_VREG_CASE(229) CLOBBER_VREG_CASE(230) CLOBBER_VREG_CASE(231)
        CLOBBER_VREG_CASE(232) CLOBBER_VREG_CASE(233) CLOBBER_VREG_CASE(234) CLOBBER_VREG_CASE(235) CLOBBER_VREG_CASE(236) CLOBBER_VREG_CASE(237) CLOBBER_VREG_CASE(238) CLOBBER_VREG_CASE(239)
        CLOBBER_VREG_CASE(240) CLOBBER_VREG_CASE(241) CLOBBER_VREG_CASE(242) CLOBBER_VREG_CASE(243) CLOBBER_VREG_CASE(244) CLOBBER_VREG_CASE(245) CLOBBER_VREG_CASE(246) CLOBBER_VREG_CASE(247)
        CLOBBER_VREG_CASE(248) CLOBBER_VREG_CASE(249) CLOBBER_VREG_CASE(250) CLOBBER_VREG_CASE(251) CLOBBER_VREG_CASE(252) CLOBBER_VREG_CASE(253) CLOBBER_VREG_CASE(254) CLOBBER_VREG_CASE(255)
    }
#undef CLOBBER_VREG_CASE
    // clang-format on
}

// ── Range operations ──

template <int START, int END> __device__ __forceinline__ void reserve_vgpr_range() {
    if constexpr (START <= END) {
        clobber_vgpr_one<START>();
        if constexpr (START < END)
            reserve_vgpr_range<START + 1, END>();
    }
}

} // namespace primus_turbo::device
