/* ************************************************************************
 * Copyright (C) 2025-2026 Advanced Micro Devices, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * ************************************************************************ */

#include "ir/passes/ToStinkyAsmPass.hpp"
#include "ErrorHandling.hpp"
#include "ir/StinkyInstructions.hpp"
#include "ir/asm/StinkyAsmIR.hpp"
#include "isa/ArchHelper.hpp"
#include <string>

namespace stinkytofu
{
    namespace
    {
        // Helper to create assembly instruction from IR
        StinkyInstruction* createAsmFromIR(IRInstruction* irInst, GfxArchID arch)
        {
            const char* logicalName = irInst->getLogicalName();

            // Get the architecture-specific mnemonic
            uint16_t    isaOpcode = 0;
            std::string mnemonic;

            // ========================================================================
            // Logical name -> mnemonic mappings (Auto-generated by TableGen)
            // ========================================================================
            //
            // All mappings are generated from tools/tablegen/GenHighLevelIR.cpp
            // This ensures consistency between IR class definitions and mnemonic mappings.
            //
            // The generated code looks like:
            //   else if(std::string(logicalName) == "VAddF32") { mnemonic = "v_add_f32"; }
            //   else if(std::string(logicalName) == "VMulF32") { mnemonic = "v_mul_f32"; }
            //   ...
            //
            if(false)
            {
                // Placeholder for generated code
            }
#include "ir/IRMnemonics_generated.inc"
            else
            {
                STINKY_UNREACHABLE(
                    ("ToStinkyAsmPass: Unknown IR instruction: " + std::string(logicalName))
                        .c_str());
                return nullptr;
            }

            // Get the ISA opcode for this mnemonic on the target architecture
            isaOpcode              = getMnemonicToIsaOpcode(mnemonic, arch);
            const HwInstDesc* desc = getMCIDByIsaOp(isaOpcode, arch);

            if(!desc)
            {
                STINKY_UNREACHABLE(
                    ("ToStinkyAsmPass: Instruction not supported on architecture: " + mnemonic)
                        .c_str());
                return nullptr;
            }

            // Create the assembly instruction
            StinkyInstruction* asmInst = new StinkyInstruction(desc);

            // Copy operands from IR to assembly
            if(!irInst->dests.empty())
            {
                asmInst->setDestRegs(irInst->dests);
            }
            if(!irInst->srcs.empty())
            {
                asmInst->setSrcRegs(irInst->srcs);
            }

            // Copy comment
            if(!irInst->comment.empty())
            {
                asmInst->addModifier(CommentData(irInst->comment));
            }

            // Handle special modifiers based on IR type
            // TODO: Copy DPP, SDWA, DS modifiers when needed

            return asmInst;
        }
    }

    std::vector<StinkyInstruction*> ToStinkyAsmPass::lower(IRInstruction* irInst, GfxArchID arch)
    {
        std::vector<StinkyInstruction*> result;

        if(!irInst)
        {
            return result;
        }

        // Check that this is not a composite instruction
        // Note: Some composite instructions may pass through if the target architecture
        // supports them natively (e.g., v_pk_add_f32 on gfx9+). These will be handled
        // by the mnemonic mapping below.
        // Composite instructions that don't have native support should have been expanded
        // by CompositeInstructionLoweringPass.

        // Convert the simple IR instruction to assembly
        StinkyInstruction* asmInst = createAsmFromIR(irInst, arch);
        if(asmInst)
        {
            result.push_back(asmInst);
        }

        return result;
    }

    std::unique_ptr<IRInstToAsmPass> createToStinkyAsmPass()
    {
        return std::make_unique<ToStinkyAsmPass>();
    }

} // namespace stinkytofu
