#!/bin/bash
# Assembly Drift Verification Script
# Compares GPU assembly between baseline (compile-time indexing)
# and optimized (runtime indexing) to verify zero drift

set -e

OUT_DIR="assembly_comparison"
mkdir -p "$OUT_DIR"

# Check if test file exists
if [ ! -f "test_runtime_buffer_prototype.cpp" ]; then
    echo "❌ ERROR: test_runtime_buffer_prototype.cpp not found"
    echo "Please create the test harness first"
    exit 1
fi

echo "======================================================================="
echo "Assembly Drift Verification for Runtime Buffer Indexing"
echo "======================================================================="
echo ""

echo "=== Step 1: Building Baseline (Compile-Time Indexing) ==="
echo "This uses the original CK pattern with static_for and Number<I>"
echo ""

hipcc -std=c++20 -O3 --offload-arch=gfx942 \
      -DUSE_BASELINE \
      -I./include \
      -save-temps=obj \
      -c test_runtime_buffer_prototype.cpp \
      -o "$OUT_DIR/baseline.o" 2>&1 | tee "$OUT_DIR/baseline_build.log"

baseline_status=$?
if [ $baseline_status -ne 0 ]; then
    echo "❌ Baseline compilation FAILED"
    echo "See $OUT_DIR/baseline_build.log for details"
    exit 1
fi

echo ""
echo "=== Step 2: Building Optimized (Runtime Indexing) ==="
echo "This uses runtime indexing with constexpr offset tables"
echo ""

hipcc -std=c++20 -O3 --offload-arch=gfx942 \
      -DUSE_RUNTIME \
      -I./include \
      -save-temps=obj \
      -c test_runtime_buffer_prototype.cpp \
      -o "$OUT_DIR/runtime.o" 2>&1 | tee "$OUT_DIR/runtime_build.log"

runtime_status=$?
if [ $runtime_status -ne 0 ]; then
    echo "❌ Runtime compilation FAILED"
    echo "See $OUT_DIR/runtime_build.log for details"
    exit 1
fi

echo ""
echo "=== Step 3: Extracting GPU Assembly ==="
echo ""

# Find assembly files generated by -save-temps=obj
baseline_asm=$(find . -name "*baseline*gfx942*.s" 2>/dev/null | head -1)
runtime_asm=$(find . -name "*runtime*gfx942*.s" 2>/dev/null | head -1)

if [ -z "$baseline_asm" ] || [ -z "$runtime_asm" ]; then
    echo "❌ ERROR: Assembly files not found"
    echo "Baseline: $baseline_asm"
    echo "Runtime: $runtime_asm"
    echo ""
    echo "Note: -save-temps=obj creates assembly files with unique names"
    echo "Try: find . -name '*gfx942*.s' to locate them"
    exit 1
fi

echo "Baseline assembly: $baseline_asm"
echo "Runtime assembly: $runtime_asm"
echo ""

# Extract GPU instructions only (ignore labels, directives, etc.)
echo "Extracting GPU instructions from baseline kernel..."
sed -n '/_Z.*test_baseline/,/^_Z[0-9]/p' "$baseline_asm" 2>/dev/null | \
    grep -E '^\s+(v_|s_|ds_|global_|flat_|buffer_)' > "$OUT_DIR/baseline.gpu_only" || true

echo "Extracting GPU instructions from runtime kernel..."
sed -n '/_Z.*test_runtime/,/^_Z[0-9]/p' "$runtime_asm" 2>/dev/null | \
    grep -E '^\s+(v_|s_|ds_|global_|flat_|buffer_)' > "$OUT_DIR/runtime.gpu_only" || true

# Check if extraction succeeded
if [ ! -s "$OUT_DIR/baseline.gpu_only" ]; then
    echo "⚠️  WARNING: No GPU instructions extracted from baseline"
    echo "Kernel symbol may be named differently"
    echo "Available kernels:"
    grep -E '^_Z.*:$' "$baseline_asm" | head -5
fi

if [ ! -s "$OUT_DIR/runtime.gpu_only" ]; then
    echo "⚠️  WARNING: No GPU instructions extracted from runtime"
    echo "Kernel symbol may be named differently"
    echo "Available kernels:"
    grep -E '^_Z.*:$' "$runtime_asm" | head -5
fi

echo ""
echo "=== Step 4: Instruction Count Comparison ==="
echo ""

baseline_count=$(wc -l < "$OUT_DIR/baseline.gpu_only" 2>/dev/null || echo "0")
runtime_count=$(wc -l < "$OUT_DIR/runtime.gpu_only" 2>/dev/null || echo "0")

echo "Baseline:  $baseline_count GPU instructions"
echo "Runtime:   $runtime_count GPU instructions"

if [ "$baseline_count" -eq "0" ] || [ "$runtime_count" -eq "0" ]; then
    echo ""
    echo "⚠️  Cannot compare - no instructions extracted"
    exit 1
fi

if [ "$baseline_count" -ne "$runtime_count" ]; then
    echo "❌ INSTRUCTION COUNT MISMATCH"
    echo "Difference: $((runtime_count - baseline_count)) instructions"
fi

echo ""
echo "=== Step 5: Assembly Diff (ignoring labels) ==="
echo ""

# Normalize branch labels (e.g., .LBB0_2 -> LABEL, .LBB1_2 -> LABEL)
sed 's/\.LBB[0-9]*_[0-9]*/LABEL/g' "$OUT_DIR/baseline.gpu_only" > "$OUT_DIR/baseline_norm.asm"
sed 's/\.LBB[0-9]*_[0-9]*/LABEL/g' "$OUT_DIR/runtime.gpu_only" > "$OUT_DIR/runtime_norm.asm"

echo "Running normalized diff..."
if diff -u "$OUT_DIR/baseline_norm.asm" "$OUT_DIR/runtime_norm.asm" > "$OUT_DIR/assembly.diff"; then
    echo ""
    echo "======================================================================="
    echo "✅ ZERO ASSEMBLY DRIFT - Assemblies are IDENTICAL"
    echo "======================================================================="
    echo ""
    echo "Runtime indexing produces the same GPU code as compile-time indexing!"
    echo "This proves that the compiler optimizes runtime indices when the values"
    echo "are known at compile time (via constexpr offset tables)."
    echo ""
    echo "Template instantiation reduction: (KPack × sites) -> (1 × sites)"
    echo "Expected benefit: 87.5% fewer template instantiations"
    exit 0
else
    echo ""
    echo "======================================================================="
    echo "❌ ASSEMBLY DRIFT DETECTED"
    echo "======================================================================="
    echo ""
    echo "Differences found (saved to $OUT_DIR/assembly.diff):"
    echo ""
    head -50 "$OUT_DIR/assembly.diff"
    echo ""
    echo "Full diff saved to: $OUT_DIR/assembly.diff"
    echo ""
    echo "This indicates runtime indexing may not be optimizing as expected."
    echo "Review the diff to understand the codegen differences."
    exit 1
fi
