extends:
  - qwen2.5_base.yaml

tokenizer_type: HuggingFaceTokenizer
tokenizer_model: Qwen/Qwen2.5-32B

# Qwen 2.5 32B specific parameters
hidden_size: 5120
ffn_hidden_size: 27648
num_layers: 64
num_attention_heads: 40
num_query_groups: 8
