extends:
  - qwen2.5_base.yaml

tokenizer_type: HuggingFaceTokenizer
tokenizer_model: Qwen/Qwen2.5-3B

# Qwen 2.5 3B specific parameters
hidden_size: 2048
ffn_hidden_size: 11008
num_layers: 36
num_attention_heads: 16
num_query_groups: 2
