#!/usr/bin/env python3
# Copyright (c) Advanced Micro Devices, Inc., or its affiliates.
# SPDX-License-Identifier: MIT

"""
Generate per-(arch,dtype) FMHA forward tile tables from the dispatcher's
`fmha_arch_specs.json` as a set of C++ source files that plug into
`ck::host::device_fmha_fwd::GetTileConfigsForHdim`.

Phase 4 of the hipRTC migration. The JSON is authoritative for the tile
shapes; wave/warp shapes default to the spec's `defaults` block when no
per-tile override is present, matching the behaviour of
`dispatcher/codegen/unified_fmha_codegen.py` at launch-time kernel
selection.

Usage:
    generate_cpp_tile_tables.py \\
        --spec path/to/fmha_arch_specs.json \\
        --output-dir path/to/output/cpp

Emits:
    output/tile_tables_<arch>_<dtype>.cpp      -- one TileMap per (arch, dtype)
    output/tile_tables_registry.cpp            -- GetTileConfigsForHdim shim

The emitted files are linked into `ck_host` alongside MGX's hand-rolled
`gfx9_fp16_tiles` and `gfx12_fp16_tiles`. The registry dispatcher
prefers MGX's curated fp16/bf16 tables on gfx9/gfx12 where they exist
(they have richer per-bucket tile variants) and falls back to the
autogenerated tables for every other (arch, dtype) pair.
"""

import argparse
import json
import sys
from pathlib import Path


# MGX-equivalent default wave/warp shapes when JSON doesn't carry per-tile
# overrides. These match the safest single-variant sweep from
# `unified_fmha_codegen.py::_canonicalize_config` when only the spec
# defaults are available. 6 values each (FWD uses only the first 6 of the
# 9-slot wave/warp defaults in the JSON).
_FWD_DEFAULT_WAVE = (2, 2, 1, 2, 2, 1)  # rm0, rn0, rk0, rm1, rn1, rk1
_FWD_DEFAULT_WARP = (32, 32, 16, 32, 32, 16)  # wm0, wn0, wk0, wm1, wn1, wk1


HEADER = """// SPDX-License-Identifier: MIT
// Auto-generated by codegen/scripts/generate_cpp_tile_tables.py.
// DO NOT EDIT. Source of truth: dispatcher/codegen/fmha_arch_specs.json.
// Part of the Phase 4 autogenerated tile-table expansion.

#include "ck/host/device_fmha_fwd/operation.hpp"

#include <unordered_map>

namespace ck {
namespace host {
namespace device_fmha_fwd {
namespace generated {

"""


def _bucket_key(bucket):
    """Convert JSON key like '128_128' to (128, 128) tuple."""
    a, b = bucket.split("_")
    return int(a), int(b)


def _emit_tile_row(tile, wave=_FWD_DEFAULT_WAVE, warp=_FWD_DEFAULT_WARP):
    """Emit a single C++ brace-initialiser for one TileConfig."""
    bm0, bn0, bk0, bn1, bk1, bk0max = tile
    rm0, rn0, rk0, rm1, rn1, rk1 = wave
    wm0, wn0, wk0, wm1, wn1, wk1 = warp
    return (
        f"    {{{bm0:>4}, {bn0:>4}, {bk0:>4}, {bn1:>4}, {bk1:>4}, {bk0max:>4},"
        f" {rm0}, {rn0}, {rk0}, {rm1}, {rn1}, {rk1},"
        f" {wm0:>2}, {wn0:>2}, {wk0:>2}, {wm1:>2}, {wn1:>2}, {wk1:>2}}},"
    )


def _safe_ident(s):
    """gfx9_4_generic -> gfx9_4_generic; fp8fp16 -> fp8fp16 etc."""
    return s.replace(".", "_").replace("-", "_")


def emit_arch_dtype_file(arch, dtype, buckets, out_path):
    """Emit one .cpp file containing a static TileMap + a registrar."""
    arch_id = _safe_ident(arch)
    dtype_id = _safe_ident(dtype)
    table_name = f"{arch_id}_{dtype_id}_tiles"

    with open(out_path, "w") as f:
        f.write(HEADER)
        f.write(f"// arch={arch}, dtype={dtype}, buckets={len(buckets)}\n")
        f.write(f"static const TileMap {table_name} = {{\n")
        for bucket_key in sorted(buckets.keys(), key=_bucket_key):
            hdim, hdim_v = _bucket_key(bucket_key)
            tile_list = buckets[bucket_key]
            f.write(f"    // bucket {hdim} x {hdim_v} ({len(tile_list)} tiles)\n")
            # One map entry = {pair_key, vector_value}. Outer braces come
            # from the map-entry-literal, inner {{...}} is the pair, inner
            # {{...}} is the vector.
            f.write(f"    {{ {{{hdim}, {hdim_v}}}, {{\n")
            for tile in tile_list:
                f.write(_emit_tile_row(tile) + "\n")
            f.write("    }},\n")
        f.write("};\n\n")
        f.write(f"const TileMap& get_{table_name}() {{ return {table_name}; }}\n")
        f.write("\n")
        f.write("} // namespace generated\n")
        f.write("} // namespace device_fmha_fwd\n")
        f.write("} // namespace host\n")
        f.write("} // namespace ck\n")


def emit_registry(triples, out_path):
    """Emit tile_tables_registry.cpp: a shim that maps (arch, dtype) to the
    autogenerated table.

    MGX's hand-rolled gfx9_fp16_tiles / gfx12_fp16_tiles remain the source
    for (gfx9*, fp16) and (gfx12*, fp16) respectively; this registry only
    serves the combinations that aren't MGX-curated.
    """
    with open(out_path, "w") as f:
        f.write(HEADER)
        f.write("// Registry shim. The public GetTileConfigsForHdim() in\n")
        f.write("// device_fmha_fwd_operation.cpp tries the MGX hand-rolled\n")
        f.write("// tables first for fp16/bf16 on gfx9/gfx12 (where they\n")
        f.write("// carry rich per-bucket variants). For other (arch, dtype)\n")
        f.write("// combinations, the public function delegates to\n")
        f.write("// lookup_generated() below.\n\n")

        for arch, dtype, _ in triples:
            arch_id = _safe_ident(arch)
            dtype_id = _safe_ident(dtype)
            f.write(f"extern const TileMap& get_{arch_id}_{dtype_id}_tiles();\n")
        f.write("\n")

        f.write("static DataType dtype_for_name(const std::string& name) {\n")
        f.write("    if(name == \"fp16\" || name == \"fp8fp16\")      return DataType::Half;\n")
        f.write("    if(name == \"bf16\" || name == \"fp8bf16\")      return DataType::Half;  // bf16 uses Half enum slot\n")
        f.write("    if(name == \"fp32\" || name == \"fp8fp32\")      return DataType::Float;\n")
        f.write("    return DataType::Half;\n")
        f.write("}\n\n")

        f.write("HdimBucketResult lookup_generated(const std::string& arch,\n")
        f.write("                                  const std::string& dtype_name,\n")
        f.write("                                  std::size_t K, std::size_t O) {\n")
        f.write("    HdimBucketResult r;\n")
        f.write("    const TileMap* tbl = nullptr;\n")

        seen = set()
        for arch, dtype, _ in triples:
            key = (arch, dtype)
            if key in seen:
                continue
            seen.add(key)
            arch_id = _safe_ident(arch)
            dtype_id = _safe_ident(dtype)
            f.write(f"    if(arch.find(\"{arch}\") == 0 && dtype_name == \"{dtype}\") ")
            f.write(f"tbl = &get_{arch_id}_{dtype_id}_tiles();\n")

        f.write("    if(tbl == nullptr) return r;\n")
        f.write("    for(const auto& [key, tiles] : *tbl) {\n")
        f.write("        if(K <= key.first && O <= key.second) {\n")
        f.write("            r.bucket_hdim   = key.first;\n")
        f.write("            r.bucket_hdim_v = key.second;\n")
        f.write("            r.tiles         = tiles;\n")
        f.write("            return r;\n")
        f.write("        }\n")
        f.write("    }\n")
        f.write("    return r;\n")
        f.write("}\n\n")

        f.write("} // namespace generated\n")
        f.write("} // namespace device_fmha_fwd\n")
        f.write("} // namespace host\n")
        f.write("} // namespace ck\n")


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--spec", required=True, type=Path)
    p.add_argument("--output-dir", required=True, type=Path)
    p.add_argument("--list-only", action="store_true",
                   help="just print what would be emitted")
    args = p.parse_args()

    spec = json.loads(args.spec.read_text())
    args.output_dir.mkdir(parents=True, exist_ok=True)

    triples = []  # (arch, dtype, num_buckets)

    for arch, arch_spec in spec["architectures"].items():
        for dtype, buckets in arch_spec["hdim_tile_combos"].items():
            triples.append((arch, dtype, len(buckets)))
            out_path = args.output_dir / f"tile_tables_{_safe_ident(arch)}_{_safe_ident(dtype)}.cpp"
            if args.list_only:
                print(f"  {arch:10s} {dtype:8s}  -> {out_path.name} ({len(buckets)} buckets)")
            else:
                emit_arch_dtype_file(arch, dtype, buckets, out_path)

    if not args.list_only:
        registry_path = args.output_dir / "tile_tables_registry.cpp"
        emit_registry(triples, registry_path)

    if not args.list_only:
        print(f"Emitted {len(triples) + 1} files to {args.output_dir}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
