#!/usr/bin/env python3

"""
Render a matrix stored in a msgpack file as an image.
"""

import argparse
import os
import sys

from lib import matrix_utils

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)

    parser.add_argument("--verbose", "-v", action="count", default=0)
    parser.add_argument("input", help="Input file")
    parser.add_argument("output", nargs="?", help="Output file")

    args = parser.parse_args()
    if args.output is None:
        (base, _) = os.path.splitext(args.input)
        args.output = base + ".png"

    if args.verbose > 0:
        print(args)

    fig = matrix_utils.showMatrix(args.input)
    fig.savefig(args.output)
