name: docs_vale_linting

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - users/dsclear/documentation_vale_linting
    paths:
      - '**/*.md'
      - '**/*.rst'
      - '.vale.ini'

jobs:
  docs-vale-linting:
    name: 'docs-vale-linting'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
      - run: npm install -g mdx2vast

      - name: install_docutils_for_vale_linting
        run: pip install docutils

      - uses: errata-ai/vale-action@v2.1.1
        with:
          fail_on_error: true
          vale_flags: "--minAlertLevel=error"
