name: TheRock CI Nightly

on:
  schedule:
    - cron: "0 7 * * *" # Runs nightly at 7 AM UTC
  workflow_dispatch:
    inputs:
      projects:
        type: string
        description: "Insert space-separated list of projects to test or 'all' to test all projects. ex: 'projects/rocprim projects/hipcub'"

permissions:
  contents: read

jobs:
  ci:
    # TODO: Update to @main after TheRock PR merges
    uses: ROCm/TheRock/.github/workflows/ci.yml@users/jayhawk-commits/deduplicate-ci
    secrets: inherit
    with:
      external_source_checkout: true
      therock_ref: users/jayhawk-commits/deduplicate-ci
    permissions:
      contents: read
      id-token: write
