name: TheRock CI

on:
  push:
    branches:
      - develop
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  workflow_dispatch:
    inputs:
      projects:
        type: string
        description: "Insert space-separated list of projects to test or 'all' to test all projects. ex: 'projects/rocprim projects/hipcub'"
  workflow_call:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  ci:
    # TODO: Update to @main after TheRock PR merges
    uses: ROCm/TheRock/.github/workflows/ci.yml@users/jayhawk-commits/deduplicate-ci
    secrets: inherit
    with:
      external_source_checkout: true
      therock_ref: users/jayhawk-commits/deduplicate-ci
    permissions:
      contents: read
      id-token: write
